import { Camera, CameraOff, Mic, MicOff } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

export function MeetingPreflightPage() {
  const roomId = Number(useParams().roomId); const navigate = useNavigate(); const videoRef = useRef<HTMLVideoElement>(null); const streamRef = useRef<MediaStream | null>(null);
  const [audio, setAudio] = useState(true); const [video, setVideo] = useState(true); const [devices, setDevices] = useState<MediaDeviceInfo[]>([]); const [audioDeviceId, setAudioDeviceId] = useState(""); const [videoDeviceId, setVideoDeviceId] = useState(""); const [error, setError] = useState("");
  useEffect(() => { let active = true; const preview = async () => { streamRef.current?.getTracks().forEach((track) => track.stop()); try { const stream = await navigator.mediaDevices.getUserMedia({ audio: audio ? (audioDeviceId ? { deviceId: { exact: audioDeviceId } } : true) : false, video: video ? (videoDeviceId ? { deviceId: { exact: videoDeviceId } } : true) : false }); if (!active) return; streamRef.current = stream; if (videoRef.current) videoRef.current.srcObject = stream; setDevices(await navigator.mediaDevices.enumerateDevices()); setError(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "无法访问媒体设备"); } }; if (audio || video) void preview(); else { streamRef.current?.getTracks().forEach((track) => track.stop()); streamRef.current = null; } return () => { active = false; streamRef.current?.getTracks().forEach((track) => track.stop()); }; }, [audio, video, audioDeviceId, videoDeviceId]);
  useEffect(() => { const changed = () => void navigator.mediaDevices.enumerateDevices().then(setDevices); navigator.mediaDevices?.addEventListener("devicechange", changed); return () => navigator.mediaDevices?.removeEventListener("devicechange", changed); }, []);
  const enter = () => { sessionStorage.setItem(`meeting-options:${roomId}`, JSON.stringify({ audio, video, audioDeviceId, videoDeviceId })); navigate(`/meetings/${roomId}`); };
  return <div className="preflight-page"><section className="preflight-preview"><video ref={videoRef} autoPlay muted playsInline />{!video && <div className="camera-placeholder"><CameraOff size={30} />摄像头已关闭</div>}</section><aside className="preflight-panel"><p className="eyebrow">Device check</p><h1>加入会议前</h1><p>确认麦克风与摄像头设置。</p>{error && <div className="status-error">{error}</div>}<div className="preflight-toggles"><button className={audio ? "active" : ""} onClick={() => setAudio(!audio)}>{audio ? <Mic size={18} /> : <MicOff size={18} />}麦克风</button><button className={video ? "active" : ""} onClick={() => setVideo(!video)}>{video ? <Camera size={18} /> : <CameraOff size={18} />}摄像头</button></div><label>麦克风<select className="field" value={audioDeviceId} onChange={(event) => setAudioDeviceId(event.target.value)}><option value="">系统默认</option>{devices.filter((item) => item.kind === "audioinput").map((item) => <option key={item.deviceId} value={item.deviceId}>{item.label || "麦克风"}</option>)}</select></label><label>摄像头<select className="field" value={videoDeviceId} onChange={(event) => setVideoDeviceId(event.target.value)}><option value="">系统默认</option>{devices.filter((item) => item.kind === "videoinput").map((item) => <option key={item.deviceId} value={item.deviceId}>{item.label || "摄像头"}</option>)}</select></label><button className="button-primary w-full" onClick={enter}>进入会议</button></aside></div>;
}
