/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listRefreshSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeRefreshSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/send-verification-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["sendVerificationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/email/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyEmailCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listBlocks"];
        put?: never;
        post: operations["blockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/blocks/{blockedUserId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["unblockUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/deletion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deleteAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPushDevices"];
        put?: never;
        post: operations["registerPushDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deletePushDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entitlements/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyEntitlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentLegal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/legal/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptCurrentLegal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrganizations"];
        put?: never;
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}/switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["switchOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/invites/{code}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["acceptOrganizationInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/realtime/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a 60-second, channel-bound, single-use WebSocket ticket. */
        post: operations["issueRealtimeTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webrtc/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWebRTCConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIError: {
            /** @constant */
            success: false;
            code?: string;
            error: string;
            request_id?: string;
        };
        User: {
            /** Format: int64 */
            id: number;
            /** Format: email */
            email: string;
            display_name: string;
        };
        Organization: {
            /** Format: int64 */
            id: number;
            name: string;
            slug?: string;
            description?: string;
            /** @enum {string} */
            role: "owner" | "admin" | "member";
        };
        AuthResponse: {
            user: components["schemas"]["User"];
            access_token: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
            accept_current_legal: boolean;
        };
        VerificationCodeRequest: {
            /** Format: email */
            email: string;
            /** @enum {string} */
            purpose: "register" | "password_reset" | "account_deletion";
        };
        VerifyCodeRequest: components["schemas"]["VerificationCodeRequest"] & {
            code: string;
        };
        PasswordResetRequest: {
            /** Format: email */
            email: string;
            code: string;
            new_password: string;
            confirm_password: string;
        };
        LegalInfo: {
            terms_version: string;
            privacy_version: string;
            terms_url: string;
            privacy_policy_url: string;
            /** Format: email */
            support_email: string;
            account_deletion_url: string;
        };
        RefreshSession: {
            /** Format: int64 */
            id: number;
            status: string;
            current: boolean;
            user_agent: string;
            ip_address: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
            invalid_use_count: number;
            /** Format: date-time */
            last_invalid_use_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserBlock: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            blocked_user_id: number;
            blocked_user_email?: string;
            blocked_user_display_name?: string;
            blocked_user_status?: string;
            /** Format: date-time */
            blocked_user_deleted_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        RegisterPushDeviceRequest: {
            token: string;
            /** @default fcm */
            provider: string;
            /** @enum {string} */
            platform?: "web" | "android" | "ios";
            device_name?: string;
            app_version?: string;
        };
        PushDevice: {
            /** Format: int64 */
            id: number;
            provider: string;
            platform: string;
            device_name: string;
            app_version: string;
            /** Format: date-time */
            last_registered: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserEntitlement: {
            /** Format: int64 */
            id: number;
            entitlement: string;
            tier: string;
            product_id?: string;
            status: string;
            /** Format: date-time */
            expires_at?: string | null;
            source: string;
        };
        UsageSnapshot: {
            feature: string;
            period_key: string;
            unit: string;
            /** Format: int64 */
            used_units: number;
            /** Format: int64 */
            limit_units: number;
            unlimited: boolean;
            /** Format: int64 */
            remaining_units: number;
        };
        Conversation: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            team_id?: number | null;
            /** Format: int64 */
            room_id?: number | null;
            type: string;
            title: string;
            topic?: string;
            status: string;
            /** Format: int64 */
            assignee_user_id?: number | null;
            assignee_email?: string;
            assignee_display_name?: string;
            priority: string;
            /** Format: int64 */
            contact_id?: number | null;
            /** Format: date-time */
            last_internal_note_at?: string | null;
            /** Format: date-time */
            last_message_at?: string | null;
            last_message_preview?: string;
            last_message_type?: string;
            unread_count: number;
            /** Format: int64 */
            active_room_id?: number | null;
            active_room_title?: string;
            /** Format: int64 */
            latest_room_id?: number | null;
            latest_room_title?: string;
            /** Format: int64 */
            latest_recording_id?: number | null;
        };
        Message: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            conversation_id: number;
            /** Format: int64 */
            sender_id: number;
            sender_email: string;
            sender_display_name: string;
            type: string;
            body: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        ConversationNote: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            conversation_id: number;
            /** Format: int64 */
            author_id: number;
            author_email: string;
            author_display_name: string;
            body: string;
            /** Format: date-time */
            created_at: string;
        };
        ConversationDetail: {
            conversation: components["schemas"]["Conversation"];
            latest_note?: components["schemas"]["ConversationNote"] | null;
            latest_followup?: {
                [key: string]: unknown;
            } | null;
            workspace: {
                latest_recording?: {
                    [key: string]: unknown;
                } | null;
                meeting_summary?: {
                    [key: string]: unknown;
                } | null;
                latest_note?: components["schemas"]["ConversationNote"] | null;
                agent_context: {
                    transcript_segment_count: number;
                    meeting_transcription_status?: string;
                    meeting_transcription_error?: string;
                    meeting_transcript_segment_count?: number;
                    /** Format: date-time */
                    latest_meeting_transcript_at?: string | null;
                    /** Format: date-time */
                    last_agent_run_at?: string | null;
                    last_agent_status?: string;
                    pending_approval_count?: number;
                    knowledge_source_count?: number;
                    latest_memory_keys?: string[];
                };
                /** Format: int64 */
                assignee_user_id?: number | null;
                assignee_label?: string;
                status: string;
                priority: string;
            };
        };
        ContactProfile: {
            company?: string;
            role?: string;
            timezone?: string;
            default_source_lang?: string;
            default_target_lang?: string;
            relationship_status?: string;
            preferred_contact_start?: string;
            preferred_contact_end?: string;
            preferred_contact_days?: string;
            last_followup_state?: string;
            note?: string;
        };
        Contact: components["schemas"]["User"] & {
            status?: string;
            /** Format: date-time */
            deleted_at?: string | null;
            profile?: components["schemas"]["ContactProfile"];
        };
        FollowUpTask: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            peer_user_id: number;
            call_id?: string;
            type: string;
            status: string;
            title: string;
            description?: string;
            /** Format: date-time */
            due_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            reminder_mode?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        FollowUpItem: {
            task: components["schemas"]["FollowUpTask"];
            peer?: components["schemas"]["User"] | null;
            contact?: components["schemas"]["ContactProfile"] | null;
            is_overdue: boolean;
        };
        PipelineStage: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            pipeline_id: number;
            name: string;
            position: number;
            is_closed: boolean;
        };
        Pipeline: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            name: string;
            is_default: boolean;
            stages: components["schemas"]["PipelineStage"][];
        };
        Deal: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            pipeline_id: number;
            /** Format: int64 */
            stage_id?: number | null;
            stage_name?: string;
            /** Format: int64 */
            owner_id: number;
            title: string;
            description?: string;
            status: string;
            /** Format: int64 */
            value_cents: number;
            currency: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DealActivity: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            deal_id: number;
            type: string;
            reference_type: string;
            reference_id: string;
            summary: string;
            metadata_json?: string;
            /** Format: int64 */
            created_by: number;
            /** Format: date-time */
            created_at: string;
        };
        CallHistory: {
            /** Format: int64 */
            id: number;
            call_id: string;
            /** Format: int64 */
            caller_id: number;
            /** Format: int64 */
            callee_id: number;
            caller_email: string;
            callee_email: string;
            caller_display_name: string;
            callee_display_name: string;
            status: string;
            end_reason: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            answered_at?: string | null;
            /** Format: date-time */
            ended_at?: string | null;
            followup_status?: string;
            /** Format: date-time */
            next_task_due_at?: string | null;
            is_overdue?: boolean;
        };
        RealtimeTicket: {
            ticket: string;
            /** @enum {string} */
            channel: "chat" | "signaling";
            /** Format: date-time */
            expires_at: string;
            websocket_path: string;
        };
        RoomMember: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            room_id: number;
            /** Format: int64 */
            user_id: number;
            role: string;
            user_email?: string;
            user_display_name?: string;
            joined?: boolean;
            left?: boolean;
            audio_enabled?: boolean;
            video_enabled?: boolean;
            connection_state?: string;
            is_host?: boolean;
            /** Format: date-time */
            joined_at?: string | null;
            /** Format: date-time */
            left_at?: string | null;
        };
        RecordingSession: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            room_id: number;
            /** Format: int64 */
            started_by: number;
            status: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            stopped_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Room: {
            room: {
                /** Format: int64 */
                id: number;
                /** Format: int64 */
                organization_id: number;
                /** Format: int64 */
                team_id?: number | null;
                /** Format: int64 */
                conversation_id?: number | null;
                title: string;
                status: string;
                /** Format: int64 */
                created_by: number;
                /** Format: date-time */
                started_at?: string | null;
                /** Format: date-time */
                ended_at?: string | null;
                /** Format: date-time */
                created_at: string;
                /** Format: date-time */
                updated_at: string;
            };
            members: components["schemas"]["RoomMember"][];
            events: {
                [key: string]: unknown;
            }[];
            active_recording?: components["schemas"]["RecordingSession"] | null;
            /** Format: int64 */
            conversation_id?: number | null;
            conversation_title?: string;
            participant_count: number;
            is_active: boolean;
            has_recording: boolean;
            /** Format: int64 */
            latest_recording_id?: number | null;
        };
        RecordingFile: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            recording_session_id: number;
            storage_driver: string;
            storage_bucket?: string;
            object_key: string;
            etag?: string;
            content_type: string;
            /** Format: date-time */
            retention_until?: string | null;
            /** Format: date-time */
            deleted_at?: string | null;
            duration_seconds: number;
            metadata_json?: string;
            /** Format: date-time */
            created_at: string;
            download_url: string;
            file_name: string;
            /** Format: int64 */
            file_size_bytes: number;
            recording_kind: string;
        };
        RecordingTranscription: {
            /** Format: int64 */
            id: number;
            /** @enum {string} */
            status: "pending" | "processing" | "ready" | "failed" | "skipped";
            provider?: string;
            segment_count: number;
            error_message?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        Recording: {
            session: components["schemas"]["RecordingSession"];
            files: components["schemas"]["RecordingFile"][];
            transcription?: components["schemas"]["RecordingTranscription"] | null;
        };
        MeetingTranscriptSegment: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            conversation_id: number;
            /** Format: int64 */
            room_id: number;
            /** Format: int64 */
            recording_session_id: number;
            /** Format: int64 */
            recording_file_id: number;
            /** Format: int64 */
            speaker_user_id?: number | null;
            track_key?: string;
            source: string;
            provider?: string;
            language?: string;
            text: string;
            /** Format: int64 */
            start_ms: number;
            /** Format: int64 */
            end_ms: number;
            confidence: number;
            /** Format: date-time */
            created_at: string;
        };
        RecordingTranscriptPage: {
            transcription?: components["schemas"]["RecordingTranscription"] | null;
            segments: components["schemas"]["MeetingTranscriptSegment"][];
            /** Format: int64 */
            next_after_id?: number | null;
        };
        AgentRun: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            conversation_id: number;
            source: string;
            status: string;
            goal: string;
            summary: string;
            action_items: string[];
            next_step: string;
            risk_flags: string[];
            error_message?: string;
            attempts: number;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AgentStep: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            run_id: number;
            name: string;
            status: string;
            input_json?: string;
            output_json?: string;
            error_message?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AgentToolCall: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            run_id: number;
            /** Format: int64 */
            step_id?: number | null;
            tool_name: string;
            status: string;
            input_json?: string;
            output_json?: string;
            error_message?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AgentCitation: {
            chunk_id?: string;
            source_type: string;
            source_id: string;
            source_title?: string;
            title: string;
            snippet: string;
            origin_type?: string;
            origin_url?: string;
            /** Format: int64 */
            conversation_id?: number;
            /** Format: int64 */
            knowledge_source_id?: number;
            version?: number;
            retrieval_mode?: string;
            score: number;
            /** Format: int64 */
            recording_session_id?: number;
            /** Format: int64 */
            recording_file_id?: number;
            /** Format: int64 */
            transcript_segment_id?: number;
            /** Format: int64 */
            start_ms?: number;
            /** Format: int64 */
            end_ms?: number;
        };
        AgentRunResult: {
            run: components["schemas"]["AgentRun"];
            steps: components["schemas"]["AgentStep"][];
            tool_calls: components["schemas"]["AgentToolCall"][];
            trace: {
                [key: string]: unknown;
            }[];
            citations: components["schemas"]["AgentCitation"][];
        };
        WorkflowRun: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            user_id: number;
            /** Format: int64 */
            conversation_id: number;
            /** Format: int64 */
            agent_run_id?: number | null;
            status: string;
            workflow_type?: string;
            workflow_version?: string;
            preset?: string;
            state_json?: string;
            goal: string;
            summary: string;
            action_items: string[];
            next_step: string;
            risk_flags: string[];
            error_message?: string;
            attempts: number;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            completed_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WorkflowTask: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            workflow_run_id: number;
            /** Format: int64 */
            organization_id: number;
            name: string;
            role: string;
            status: string;
            depends_on_json?: string;
            input_json?: string;
            output_json?: string;
            error_message?: string;
            attempts: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ToolApproval: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            workflow_run_id: number;
            /** Format: int64 */
            task_id: number;
            /** Format: int64 */
            organization_id: number;
            tool_call_id: string;
            tool_name: string;
            status: string;
            input_json?: string;
            output_json?: string;
            error_message?: string;
            /** Format: int64 */
            requested_by: number;
            /** Format: int64 */
            decided_by?: number | null;
            decision?: string;
            /** Format: date-time */
            requested_at: string;
            /** Format: date-time */
            decided_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WorkflowResult: {
            workflow: components["schemas"]["WorkflowRun"];
            tasks: components["schemas"]["WorkflowTask"][];
            messages: {
                [key: string]: unknown;
            }[];
            approvals: components["schemas"]["ToolApproval"][];
            history: {
                [key: string]: unknown;
            }[];
            signals: {
                [key: string]: unknown;
            }[];
            timers: {
                [key: string]: unknown;
            }[];
            citations: components["schemas"]["AgentCitation"][];
        };
        KnowledgeSource: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            conversation_id?: number | null;
            /** Format: int64 */
            created_by: number;
            /** Format: int64 */
            source_group_id?: number | null;
            /** Format: int64 */
            canonical_source_id?: number | null;
            kind: string;
            title: string;
            uri?: string;
            file_name?: string;
            content_type?: string;
            authority_score: number;
            authority_label?: string;
            dedupe_status: string;
            status: string;
            /** Format: int64 */
            active_version_id?: number | null;
            last_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        KnowledgeSourceVersion: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            source_id: number;
            version: number;
            content_hash: string;
            normalized_hash?: string;
            status: string;
            chunk_count: number;
            last_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            /** Format: date-time */
            activated_at?: string | null;
        };
        RAGChunk: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            source_id: number;
            /** Format: int64 */
            source_version_id: number;
            chunk_index: number;
            start_offset: number;
            end_offset: number;
            content_hash: string;
            snippet: string;
            index_status: string;
            last_error?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        KnowledgeSourceDetail: {
            source: components["schemas"]["KnowledgeSource"];
            versions: components["schemas"]["KnowledgeSourceVersion"][];
            chunks: components["schemas"]["RAGChunk"][];
        };
        SourceGroup: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            canonical_source_id?: number | null;
            title: string;
            status: string;
            authority_score: number;
            authority_label?: string;
            /** Format: int64 */
            created_by: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DuplicateCandidate: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            /** Format: int64 */
            source_group_id?: number | null;
            /** Format: int64 */
            source_id: number;
            /** Format: int64 */
            candidate_source_id: number;
            duplicate_kind: string;
            similarity: number;
            status: string;
            decision?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DeadLetter: {
            /** Format: int64 */
            id: number;
            aggregate_type: string;
            /** Format: int64 */
            aggregate_id: number;
            event: string;
            payload_json: string;
            idempotency_key: string;
            request_id?: string;
            status: string;
            attempts: number;
            last_error?: string;
            /** Format: date-time */
            available_at?: string | null;
            /** Format: date-time */
            updated_at: string;
        };
    };
    responses: {
        /** @description Authenticated. */
        Auth: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthResponse"];
            };
        };
        /** @description Error. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Success. */
        Success: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    success?: boolean;
                    message?: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: {
        Login: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        Register: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Login"];
        responses: {
            200: components["responses"]["Auth"];
            401: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Register"];
        responses: {
            201: components["responses"]["Auth"];
            400: components["responses"]["Error"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Auth"];
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    listRefreshSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active and historical browser sessions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sessions: components["schemas"]["RefreshSession"][];
                    };
                };
            };
        };
    };
    revokeRefreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    sendPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Success"];
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
        };
    };
    sendVerificationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificationCodeRequest"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
        };
    };
    verifyEmailCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeRequest"];
            };
        };
        responses: {
            200: components["responses"]["Success"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        user: components["schemas"]["User"];
                    };
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    listBlocks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Blocked users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        blocks: components["schemas"]["UserBlock"][];
                    };
                };
            };
        };
    };
    blockUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Success"];
        };
    };
    unblockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blockedUserId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    reportUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: components["responses"]["Success"];
        };
    };
    deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    listPushDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered push devices for the current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["PushDevice"][];
                    };
                };
            };
        };
    };
    registerPushDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPushDeviceRequest"];
            };
        };
        responses: {
            /** @description Push device registered. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                        device: components["schemas"]["PushDevice"];
                    };
                };
            };
        };
    };
    deletePushDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    getMyEntitlements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend-authoritative subscription entitlements. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        tier: "free" | "premium";
                        entitlements: components["schemas"]["UserEntitlement"][];
                    };
                };
            };
        };
    };
    getMyUsage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current feature usage ledgers. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        usage: components["schemas"]["UsageSnapshot"][];
                    };
                };
            };
        };
    };
    getCurrentLegal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current legal document versions and links. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        legal: components["schemas"]["LegalInfo"];
                    };
                };
            };
        };
    };
    acceptCurrentLegal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organizations. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organizations: components["schemas"]["Organization"][];
                    };
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created organization. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organization: components["schemas"]["Organization"];
                    };
                };
            };
        };
    };
    switchOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Selected organization. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        organization: components["schemas"]["Organization"];
                    };
                };
            };
        };
    };
    acceptOrganizationInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Success"];
        };
    };
    issueRealtimeTicket: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    channel: "chat" | "signaling";
                };
            };
        };
        responses: {
            /** @description Realtime ticket issued. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeTicket"];
                };
            };
        };
    };
    getWebRTCConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ICE/TURN configuration. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ice_servers: {
                            urls: string[];
                            username?: string;
                            credential?: string;
                        }[];
                    };
                };
            };
        };
    };
}
