listening-port=3478
tls-listening-port=443

realm=turn.example.com
fingerprint
lt-cred-mech

user=allcallall:strongpassword

cert=/etc/coturn/ssl/fullchain.pem
pkey=/etc/coturn/ssl/privkey.pem

no-tlsv1
no-tlsv1_1

min-port=49152
max-port=49200
