import * as Tabs from "@radix-ui/react-tabs";
import "@xyflow/react/dist/style.css";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, FileText, GitBranch, Play, Search, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useSearchParams } from "react-router-dom";

import { createAgentRun, createWorkflow, decideApproval, getAgentRun, getWorkflow, listApprovals, listWorkflows, processWorkflow, streamAgentRun, submitAgentToolOutputs, type AgentCitation } from "@/api/agent";
import { listConversations } from "@/api/collaboration";
import { FormError } from "@/components/AuthLayout";
import { PageError, PageLoading } from "@/components/PageState";
import { useOrganization } from "@/organizations/OrganizationContext";
import { ApprovalList, CitationCard, RerankPanel, ResultView, TraceView, WorkflowGraph } from "@/pages/agent/AgentLabPanels";
import { extractAgenticRAG, sourceLabel, workflowRuntimeLabel } from "@/pages/agent/AgentLabUtils";

const terminal = new Set(["ready", "failed", "requires_action"]);
const presets = [{ value: "meeting_brief", label: "会议复盘" }, { value: "follow_up", label: "跟进建议" }, { value: "risk_review", label: "风险审查" }];
const presetValues = new Set(presets.map((item) => item.value));

export function AgentLabPage() {
  const { activeOrganization } = useOrganization(); const orgId = activeOrganization?.id; const queryClient = useQueryClient(); const [params, setParams] = useSearchParams();
  const conversations = useQuery({ queryKey: ["organizations", orgId, "conversations", "agent"], queryFn: () => listConversations("open"), enabled: Boolean(orgId) });
  const selectedId = Number(params.get("conversationId")) || conversations.data?.[0]?.id || 0; const requestedPreset = params.get("preset") ?? ""; const preset = presetValues.has(requestedPreset) ? requestedPreset : "meeting_brief"; const [mode, setMode] = useState<"react" | "workflow">(params.get("mode") === "react" ? "react" : "workflow"); const [goal, setGoal] = useState(params.get("goal") || "请基于会议转写和会话上下文，输出会议摘要、风险点、行动项和引用来源。"); const [runId, setRunId] = useState(0); const [workflowId, setWorkflowId] = useState(0); const [streamEvents, setStreamEvents] = useState<Array<Record<string, unknown>>>([]);
  const workflows = useQuery({ queryKey: ["organizations", orgId, "agent", "workflows", selectedId], queryFn: () => listWorkflows(selectedId), enabled: Boolean(orgId && selectedId), refetchInterval: 5000 });
  const approvals = useQuery({ queryKey: ["organizations", orgId, "agent", "approvals"], queryFn: () => listApprovals(), enabled: Boolean(orgId), refetchInterval: 5000 });
  const run = useQuery({ queryKey: ["organizations", orgId, "agent", "runs", runId], queryFn: () => getAgentRun(runId), enabled: Boolean(runId), refetchInterval: (query) => terminal.has(query.state.data?.run.status ?? "") ? false : 2000 });
  const activeWorkflowId = workflowId || workflows.data?.[0]?.workflow.id || 0;
  const workflow = useQuery({ queryKey: ["organizations", orgId, "agent", "workflows", activeWorkflowId], queryFn: () => getWorkflow(activeWorkflowId), enabled: Boolean(activeWorkflowId), refetchInterval: (query) => terminal.has(query.state.data?.workflow.status ?? "") ? false : 2500 });
  const start = useMutation({ mutationFn: async () => mode === "react" ? createAgentRun(selectedId, goal) : createWorkflow(selectedId, goal, preset), onSuccess: (result) => { if ("run" in result) { setRunId(result.run.id); setStreamEvents([]); } else { setWorkflowId(result.workflow.id); void queryClient.invalidateQueries({ queryKey: ["organizations", orgId, "agent", "workflows"] }); } } });
  const process = useMutation({ mutationFn: () => processWorkflow(activeWorkflowId), onSuccess: () => void workflow.refetch() });
  const decision = useMutation({ mutationFn: ({ id, value }: { id: number; value: "approve" | "reject" }) => decideApproval(id, value), onSuccess: () => { void approvals.refetch(); void workflow.refetch(); } });
  const agentDecision = useMutation({ mutationFn: ({ callId, value }: { callId: string; value: "approve" | "reject" }) => submitAgentToolOutputs(runId, callId, value), onSuccess: (result) => { queryClient.setQueryData(["organizations", orgId, "agent", "runs", runId], result); void run.refetch(); } });

  useEffect(() => { if (!runId) return; const controller = new AbortController(); const refreshRun = () => queryClient.invalidateQueries({ queryKey: ["organizations", orgId, "agent", "runs", runId] }); void streamAgentRun(runId, controller.signal, (event) => { setStreamEvents((items) => [...items.slice(-199), event]); void refreshRun(); }).catch(() => { if (!controller.signal.aborted) void refreshRun(); }); return () => controller.abort(); }, [runId, orgId, queryClient]);

  const runtimeLabel = workflowRuntimeLabel(workflow.data?.workflow.state_json); const citations = run.data?.citations ?? workflow.data?.citations ?? []; const groupedCitations = citations.reduce<Record<string, AgentCitation[]>>((groups, citation) => { (groups[citation.source_type] ??= []).push(citation); return groups; }, {}); const agenticRAG = extractAgenticRAG(workflow.data?.tasks ?? []);
  return <div className="agent-lab"><header className="agent-header"><div><p className="eyebrow">Agent Lab</p><h1>运行与审计</h1></div><label>会话<select className="field" value={selectedId} onChange={(event) => setParams({ conversationId: event.target.value, preset })}>{conversations.data?.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></header>
    <Tabs.Root className="agent-tabs" defaultValue="run"><Tabs.List className="agent-tab-list"><Tabs.Trigger value="run"><Play size={16} />运行</Tabs.Trigger><Tabs.Trigger value="graph"><GitBranch size={16} />任务图</Tabs.Trigger><Tabs.Trigger value="rag"><Search size={16} />RAG/Rerank</Tabs.Trigger><Tabs.Trigger value="approvals"><ShieldCheck size={16} />审批 <span>{approvals.data?.filter((item) => item.status === "pending").length ?? 0}</span></Tabs.Trigger><Tabs.Trigger value="citations"><FileText size={16} />引用</Tabs.Trigger></Tabs.List>
      <Tabs.Content value="run" className="agent-tab-content"><div className="agent-run-grid"><section className="panel panel-body"><div className="segmented"><button className={mode === "react" ? "active" : ""} onClick={() => setMode("react")}>ReAct</button><button className={mode === "workflow" ? "active" : ""} onClick={() => setMode("workflow")}>Workflow</button></div>{mode === "workflow" && <label className="agent-field">Preset<select className="field" value={preset} onChange={(event) => { if (selectedId) setParams({ conversationId: String(selectedId), preset: event.target.value }); }}>{presets.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>}<label className="agent-field">目标<textarea className="field" rows={6} value={goal} onChange={(event) => setGoal(event.target.value)} /></label><FormError error={start.error || agentDecision.error} /><button className="button-primary w-full" disabled={!selectedId || start.isPending} onClick={() => start.mutate()}><Bot size={17} />启动 {mode === "react" ? "ReAct" : "Workflow"}</button></section><section className="panel trace-panel"><TraceView run={run.data} workflow={workflow.data} events={streamEvents} runtimeLabel={runtimeLabel} deciding={agentDecision.isPending} onAgentDecision={(callId, value) => agentDecision.mutate({ callId, value })} />{Boolean(activeWorkflowId) && workflow.data && !terminal.has(workflow.data.workflow.status) && <button className="button-secondary mx-4 mb-4" onClick={() => process.mutate()}>推进 Workflow</button>}</section><aside className="panel result-panel"><ResultView summary={run.data?.run.summary || workflow.data?.workflow.summary} risks={run.data?.run.risk_flags || workflow.data?.workflow.risk_flags} actions={run.data?.run.action_items || workflow.data?.workflow.action_items} next={run.data?.run.next_step || workflow.data?.workflow.next_step} status={run.data?.run.status || workflow.data?.workflow.status} runtimeLabel={runtimeLabel} /></aside></div></Tabs.Content>
      <Tabs.Content value="graph" className="agent-tab-content"><WorkflowGraph tasks={workflow.data?.tasks ?? []} /> </Tabs.Content>
      <Tabs.Content value="rag" className="agent-tab-content"><RerankPanel citations={citations} agenticRAG={agenticRAG} /></Tabs.Content>
      <Tabs.Content value="approvals" className="agent-tab-content"><ApprovalList approvals={approvals.data ?? []} loading={approvals.isLoading} decide={(id, value) => decision.mutate({ id, value })} /></Tabs.Content>
      <Tabs.Content value="citations" className="agent-tab-content"><div className="citation-groups">{Object.entries(groupedCitations).map(([source, items]) => <section key={source}><h2>{sourceLabel(source)}<span>{items?.length ?? 0}</span></h2>{items?.map((citation) => <CitationCard key={`${citation.source_type}-${citation.source_id}`} citation={citation} />)}</section>)}</div></Tabs.Content>
    </Tabs.Root>
    <aside className="run-history"><h2>运行历史</h2>{workflows.isLoading ? <PageLoading /> : workflows.isError ? <PageError error={workflows.error} /> : workflows.data?.map((item) => <button className={activeWorkflowId === item.workflow.id ? "active" : ""} key={item.workflow.id} onClick={() => setWorkflowId(item.workflow.id)}><strong>{item.workflow.preset || "workflow"} #{item.workflow.id}</strong><span>{item.workflow.status} · {new Date(item.workflow.created_at).toLocaleString()}</span></button>)}</aside>
  </div>;
}
