import * as Tabs from "@radix-ui/react-tabs";
import { Background, Controls, ReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Bot, Check, FileText, GitBranch, Play, ShieldCheck, X } from "lucide-react";
import { useEffect, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";

import { createAgentRun, createWorkflow, decideApproval, getAgentRun, getWorkflow, listApprovals, listWorkflows, processWorkflow, streamAgentRun, type AgentCitation, type WorkflowTask } from "@/api/agent";
import { listConversations } from "@/api/collaboration";
import { FormError } from "@/components/AuthLayout";
import { PageError, PageLoading } from "@/components/PageState";
import { useOrganization } from "@/organizations/OrganizationProvider";

const terminal = new Set(["ready", "failed", "requires_action"]);
const presets = [{ value: "meeting_brief", label: "会议复盘" }, { value: "follow_up", label: "跟进建议" }, { value: "risk_review", label: "风险审查" }];
const presetValues = new Set(presets.map((item) => item.value));

export function AgentLabPage() {
  const { activeOrganization } = useOrganization(); const orgId = activeOrganization?.id; const queryClient = useQueryClient(); const [params, setParams] = useSearchParams();
  const conversations = useQuery({ queryKey: ["organizations", orgId, "conversations", "agent"], queryFn: () => listConversations("open"), enabled: Boolean(orgId) });
  const selectedId = Number(params.get("conversationId")) || conversations.data?.[0]?.id || 0; const requestedPreset = params.get("preset") ?? ""; const preset = presetValues.has(requestedPreset) ? requestedPreset : "meeting_brief"; const [mode, setMode] = useState<"react" | "workflow">("workflow"); const [goal, setGoal] = useState("请基于会议转写和会话上下文，输出会议摘要、风险点、行动项和引用来源。"); const [runId, setRunId] = useState(0); const [workflowId, setWorkflowId] = useState(0); const [streamEvents, setStreamEvents] = useState<Array<Record<string, unknown>>>([]);
  const workflows = useQuery({ queryKey: ["organizations", orgId, "agent", "workflows", selectedId], queryFn: () => listWorkflows(selectedId), enabled: Boolean(orgId && selectedId), refetchInterval: 5000 });
  const approvals = useQuery({ queryKey: ["organizations", orgId, "agent", "approvals"], queryFn: () => listApprovals(), enabled: Boolean(orgId), refetchInterval: 5000 });
  const run = useQuery({ queryKey: ["organizations", orgId, "agent", "runs", runId], queryFn: () => getAgentRun(runId), enabled: Boolean(runId), refetchInterval: (query) => terminal.has(query.state.data?.run.status ?? "") ? false : 2000 });
  const activeWorkflowId = workflowId || workflows.data?.[0]?.workflow.id || 0;
  const workflow = useQuery({ queryKey: ["organizations", orgId, "agent", "workflows", activeWorkflowId], queryFn: () => getWorkflow(activeWorkflowId), enabled: Boolean(activeWorkflowId), refetchInterval: (query) => terminal.has(query.state.data?.workflow.status ?? "") ? false : 2500 });
  const start = useMutation({ mutationFn: async () => mode === "react" ? createAgentRun(selectedId, goal) : createWorkflow(selectedId, goal, preset), onSuccess: (result) => { if ("run" in result) { setRunId(result.run.id); setStreamEvents([]); } else { setWorkflowId(result.workflow.id); void queryClient.invalidateQueries({ queryKey: ["organizations", orgId, "agent", "workflows"] }); } } });
  const process = useMutation({ mutationFn: () => processWorkflow(activeWorkflowId), onSuccess: () => void workflow.refetch() });
  const decision = useMutation({ mutationFn: ({ id, value }: { id: number; value: "approve" | "reject" }) => decideApproval(id, value), onSuccess: () => { void approvals.refetch(); void workflow.refetch(); } });

  useEffect(() => { if (!runId) return; const controller = new AbortController(); const refreshRun = () => queryClient.invalidateQueries({ queryKey: ["organizations", orgId, "agent", "runs", runId] }); void streamAgentRun(runId, controller.signal, (event) => { setStreamEvents((items) => [...items.slice(-199), event]); void refreshRun(); }).catch(() => { if (!controller.signal.aborted) void refreshRun(); }); return () => controller.abort(); }, [runId, orgId, queryClient]);

  const citations = run.data?.citations ?? workflow.data?.citations ?? []; const groupedCitations = citations.reduce<Record<string, AgentCitation[]>>((groups, citation) => { (groups[citation.source_type] ??= []).push(citation); return groups; }, {});
  return <div className="agent-lab"><header className="agent-header"><div><p className="eyebrow">Agent Lab</p><h1>运行与审计</h1></div><label>会话<select className="field" value={selectedId} onChange={(event) => setParams({ conversationId: event.target.value, preset })}>{conversations.data?.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label></header>
    <Tabs.Root className="agent-tabs" defaultValue="run"><Tabs.List className="agent-tab-list"><Tabs.Trigger value="run"><Play size={16} />运行</Tabs.Trigger><Tabs.Trigger value="graph"><GitBranch size={16} />任务图</Tabs.Trigger><Tabs.Trigger value="approvals"><ShieldCheck size={16} />审批 <span>{approvals.data?.filter((item) => item.status === "pending").length ?? 0}</span></Tabs.Trigger><Tabs.Trigger value="citations"><FileText size={16} />引用</Tabs.Trigger></Tabs.List>
      <Tabs.Content value="run" className="agent-tab-content"><div className="agent-run-grid"><section className="panel panel-body"><div className="segmented"><button className={mode === "react" ? "active" : ""} onClick={() => setMode("react")}>ReAct</button><button className={mode === "workflow" ? "active" : ""} onClick={() => setMode("workflow")}>Workflow</button></div>{mode === "workflow" && <label className="agent-field">Preset<select className="field" value={preset} onChange={(event) => { if (selectedId) setParams({ conversationId: String(selectedId), preset: event.target.value }); }}>{presets.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></label>}<label className="agent-field">目标<textarea className="field" rows={6} value={goal} onChange={(event) => setGoal(event.target.value)} /></label><FormError error={start.error} /><button className="button-primary w-full" disabled={!selectedId || start.isPending} onClick={() => start.mutate()}><Bot size={17} />启动 {mode === "react" ? "ReAct" : "Workflow"}</button></section><section className="panel trace-panel"><TraceView run={run.data} workflow={workflow.data} events={streamEvents} />{activeWorkflowId && workflow.data && !terminal.has(workflow.data.workflow.status) && <button className="button-secondary mx-4 mb-4" onClick={() => process.mutate()}>推进 Workflow</button>}</section><aside className="panel result-panel"><ResultView summary={run.data?.run.summary || workflow.data?.workflow.summary} risks={run.data?.run.risk_flags || workflow.data?.workflow.risk_flags} actions={run.data?.run.action_items || workflow.data?.workflow.action_items} next={run.data?.run.next_step || workflow.data?.workflow.next_step} status={run.data?.run.status || workflow.data?.workflow.status} /></aside></div></Tabs.Content>
      <Tabs.Content value="graph" className="agent-tab-content"><WorkflowGraph tasks={workflow.data?.tasks ?? []} /> </Tabs.Content>
      <Tabs.Content value="approvals" className="agent-tab-content"><ApprovalList approvals={approvals.data ?? []} loading={approvals.isLoading} decide={(id, value) => decision.mutate({ id, value })} /></Tabs.Content>
      <Tabs.Content value="citations" className="agent-tab-content"><div className="citation-groups">{Object.entries(groupedCitations).map(([source, items]) => <section key={source}><h2>{sourceLabel(source)}<span>{items?.length ?? 0}</span></h2>{items?.map((citation) => <CitationCard key={`${citation.source_type}-${citation.source_id}`} citation={citation} />)}</section>)}</div></Tabs.Content>
    </Tabs.Root>
    <aside className="run-history"><h2>运行历史</h2>{workflows.isLoading ? <PageLoading /> : workflows.isError ? <PageError error={workflows.error} /> : workflows.data?.map((item) => <button className={activeWorkflowId === item.workflow.id ? "active" : ""} key={item.workflow.id} onClick={() => setWorkflowId(item.workflow.id)}><strong>{item.workflow.preset || "workflow"} #{item.workflow.id}</strong><span>{item.workflow.status} · {new Date(item.workflow.created_at).toLocaleString()}</span></button>)}</aside>
  </div>;
}

function TraceView({ run, workflow, events }: { run?: Awaited<ReturnType<typeof getAgentRun>>; workflow?: Awaited<ReturnType<typeof getWorkflow>>; events: Array<Record<string, unknown>> }) { const rows = run ? [...run.steps.map((item) => ({ id: `s-${item.id}`, type: "step", name: item.name, status: item.status, detail: item.output_json })), ...run.tool_calls.map((item) => ({ id: `t-${item.id}`, type: "tool", name: item.tool_name, status: item.status, detail: item.input_json }))] : workflow?.tasks.map((item) => ({ id: `w-${item.id}`, type: item.role, name: item.name, status: item.status, detail: item.output_json })) ?? []; return <div><header className="trace-header"><h2>Trace</h2><span>{rows.length + events.length} events</span></header><div className="trace-list">{rows.map((row) => <article key={row.id}><span className={`trace-dot status-${row.status}`} /><div><header><strong>{row.name}</strong><b>{row.type}</b><em>{row.status}</em></header>{row.detail && <pre>{compactJSON(row.detail)}</pre>}</div></article>)}{events.map((event, index) => <article key={`event-${index}`}><span className="trace-dot" /><div><header><strong>{String(event.name || event.event || "event")}</strong><b>stream</b><em>{String(event.status || "")}</em></header></div></article>)}</div></div>; }
function ResultView({ summary, risks = [], actions = [], next, status }: { summary?: string; risks?: string[]; actions?: string[]; next?: string; status?: string }) { return <><header><h2>结果</h2><span className={`transcription-badge status-${status}`}>{status || "idle"}</span></header><section><h3>摘要</h3><p>{summary || "等待运行结果"}</p></section><section><h3>风险点</h3>{risks.map((item) => <p key={item}>· {item}</p>)}</section><section><h3>行动项</h3>{actions.map((item) => <p key={item}>· {item}</p>)}</section>{next && <section><h3>下一步</h3><p>{next}</p></section>}</>; }
function WorkflowGraph({ tasks }: { tasks: WorkflowTask[] }) { const nodes: Node[] = tasks.map((task, index) => ({ id: String(task.id), position: { x: (index % 3) * 250, y: Math.floor(index / 3) * 130 }, data: { label: `${task.name}\n${task.role} · ${task.status}` }, className: `workflow-node status-${task.status}` })); const byName = new Map(tasks.map((task) => [task.name, task])); const edges: Edge[] = tasks.flatMap((task) => { try { const deps = JSON.parse(task.depends_on_json || "[]") as string[]; return deps.map((name) => byName.get(name)).filter(Boolean).map((dependency) => ({ id: `${dependency!.id}-${task.id}`, source: String(dependency!.id), target: String(task.id), animated: task.status === "running" })); } catch { return []; } }); return <div className="workflow-canvas">{nodes.length ? <ReactFlow nodes={nodes} edges={edges} fitView><Background /><Controls /></ReactFlow> : <div className="pane-empty">选择一个 Workflow 查看任务图</div>}</div>; }
function ApprovalList({ approvals, loading, decide }: { approvals: Awaited<ReturnType<typeof listApprovals>>; loading: boolean; decide(id: number, value: "approve" | "reject"): void }) { const [pendingOnly, setPendingOnly] = useState(true); const visible = pendingOnly ? approvals.filter((item) => item.status === "pending") : approvals; if (loading) return <PageLoading />; return <div><div className="approval-toolbar"><h2>工具审批</h2><div className="segmented"><button className={pendingOnly ? "active" : ""} onClick={() => setPendingOnly(true)}>待处理</button><button className={!pendingOnly ? "active" : ""} onClick={() => setPendingOnly(false)}>全部</button></div></div><div className="approval-list">{visible.map((item) => <article className="panel" key={item.id}><header><div><strong>{item.tool_name}</strong><span>Workflow #{item.workflow_run_id}</span></div><span className={`transcription-badge status-${item.status}`}>{item.status}</span></header><pre>{compactJSON(item.input_json)}</pre>{item.error_message && <p className="text-danger">{item.error_message}</p>}{item.status === "pending" && <footer><button className="button-secondary" onClick={() => decide(item.id, "reject")}><X size={16} />拒绝</button><button className="button-primary" onClick={() => decide(item.id, "approve")}><Check size={16} />批准</button></footer>}</article>)}</div></div>; }
function CitationCard({ citation }: { citation: AgentCitation }) { let href = citation.origin_url || ""; if (citation.source_type === "meeting_transcript" && citation.recording_session_id) href = `/recordings/${citation.recording_session_id}?segmentId=${citation.transcript_segment_id ?? ""}&startMs=${citation.start_ms ?? ""}`; if (citation.source_type === "knowledge" && citation.knowledge_source_id) href = `/knowledge?sourceId=${citation.knowledge_source_id}`; const title = citation.source_title || citation.title || sourceLabel(citation.source_type); const content = <article className="panel citation-card"><header><strong>{title}</strong><span>{Math.round(citation.score * 100)}%</span></header><p>{citation.snippet}</p></article>; return href ? <Link aria-label={`${title} 引用`} to={href}>{content}</Link> : content; }
const compactJSON = (raw?: string) => { if (!raw) return ""; try { return JSON.stringify(JSON.parse(raw), null, 2).slice(0, 800); } catch { return raw.slice(0, 800); } };
const sourceLabel = (source: string) => ({ meeting_transcript: "会议录音转写", knowledge: "知识库", message: "会话消息", note: "内部备注", conversation: "会话上下文" }[source] ?? source);
