CREATE TABLE `users` (`id` integer PRIMARY KEY AUTOINCREMENT,`email` text NOT NULL,`password_hash` text NOT NULL,`display_name` text,`fcm_token` text,`status` text NOT NULL DEFAULT "active",`deleted_at` datetime,`created_at` datetime,`updated_at` datetime,`last_seen` datetime);
CREATE TABLE sqlite_sequence(name,seq);
CREATE INDEX `idx_users_status` ON `users`(`status`);
CREATE INDEX `idx_users_fcm_token` ON `users`(`fcm_token`);
CREATE UNIQUE INDEX `idx_users_email` ON `users`(`email`);
CREATE INDEX `idx_users_last_seen` ON `users`(`last_seen`);
CREATE INDEX `idx_users_deleted_at` ON `users`(`deleted_at`);
CREATE TABLE `refresh_sessions` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer NOT NULL,`token_hash` text NOT NULL,`user_agent` text,`ip_address` text,`expires_at` datetime NOT NULL,`last_used_at` datetime,`revoked_at` datetime,`replaced_by_id` integer,`invalid_use_count` integer NOT NULL DEFAULT 0,`last_invalid_use_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_refresh_sessions_last_used_at` ON `refresh_sessions`(`last_used_at`);
CREATE INDEX `idx_refresh_sessions_expires_at` ON `refresh_sessions`(`expires_at`);
CREATE UNIQUE INDEX `idx_refresh_sessions_token_hash` ON `refresh_sessions`(`token_hash`);
CREATE INDEX `idx_refresh_sessions_user_id` ON `refresh_sessions`(`user_id`);
CREATE INDEX `idx_refresh_sessions_last_invalid_use_at` ON `refresh_sessions`(`last_invalid_use_at`);
CREATE INDEX `idx_refresh_sessions_replaced_by_id` ON `refresh_sessions`(`replaced_by_id`);
CREATE INDEX `idx_refresh_sessions_revoked_at` ON `refresh_sessions`(`revoked_at`);
CREATE TABLE `contacts` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL DEFAULT 0,`owner_id` integer NOT NULL,`contact_id` integer NOT NULL,`created_at` datetime);
CREATE INDEX `idx_contacts_owner_id` ON `contacts`(`owner_id`);
CREATE UNIQUE INDEX `idx_org_owner_contact` ON `contacts`(`organization_id`,`owner_id`,`contact_id`);
CREATE INDEX `idx_contacts_organization_id` ON `contacts`(`organization_id`);
CREATE INDEX `idx_contacts_contact_id` ON `contacts`(`contact_id`);
CREATE TABLE `email_verification_codes` (`id` integer PRIMARY KEY AUTOINCREMENT,`email` text NOT NULL,`code` text NOT NULL,`purpose` text NOT NULL DEFAULT "register",`is_verified` numeric DEFAULT false,`verified_at` datetime,`consumed_at` datetime,`attempt_count` integer DEFAULT 0,`max_attempts` integer DEFAULT 3,`last_attempt_at` datetime,`blocked_until` datetime,`expires_at` datetime NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_email_created` ON `email_verification_codes`(`email`,`created_at`);
CREATE UNIQUE INDEX `idx_email_code` ON `email_verification_codes`(`email`,`code`);
CREATE INDEX `idx_email_verification_codes_expires_at` ON `email_verification_codes`(`expires_at`);
CREATE INDEX `idx_email_verification_codes_consumed_at` ON `email_verification_codes`(`consumed_at`);
CREATE INDEX `idx_email_verification_codes_is_verified` ON `email_verification_codes`(`is_verified`);
CREATE INDEX `idx_email_purpose` ON `email_verification_codes`(`purpose`);
CREATE TABLE `email_send_logs` (`id` integer PRIMARY KEY AUTOINCREMENT,`email` text NOT NULL,`subject` text NOT NULL,`mail_type` text NOT NULL,`status` varchar(50) DEFAULT "pending",`error_message` text,`retry_count` integer DEFAULT 0,`max_retries` integer DEFAULT 3,`next_retry_at` datetime,`created_at` datetime,`updated_at` datetime,`sent_at` datetime);
CREATE INDEX `idx_email_status` ON `email_send_logs`(`email`,`status`);
CREATE INDEX `idx_email_send_logs_created_at` ON `email_send_logs`(`created_at`);
CREATE INDEX `idx_email_send_logs_next_retry_at` ON `email_send_logs`(`next_retry_at`);
CREATE INDEX `idx_email_send_logs_mail_type` ON `email_send_logs`(`mail_type`);
CREATE TABLE `call_sessions` (`id` integer PRIMARY KEY AUTOINCREMENT,`call_id` text NOT NULL,`caller_id` integer NOT NULL,`callee_id` integer NOT NULL,`caller_email` text NOT NULL,`callee_email` text NOT NULL,`caller_display_name` text,`callee_display_name` text,`status` text NOT NULL,`end_reason` text,`started_at` datetime,`answered_at` datetime,`ended_at` datetime,`last_event_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_call_sessions_ended_at` ON `call_sessions`(`ended_at`);
CREATE INDEX `idx_call_sessions_answered_at` ON `call_sessions`(`answered_at`);
CREATE INDEX `idx_call_sessions_started_at` ON `call_sessions`(`started_at`);
CREATE INDEX `idx_call_sessions_caller_email` ON `call_sessions`(`caller_email`);
CREATE INDEX `idx_call_sessions_caller_id` ON `call_sessions`(`caller_id`);
CREATE INDEX `idx_call_sessions_last_event_at` ON `call_sessions`(`last_event_at`);
CREATE INDEX `idx_call_sessions_status` ON `call_sessions`(`status`);
CREATE INDEX `idx_call_sessions_callee_email` ON `call_sessions`(`callee_email`);
CREATE INDEX `idx_call_sessions_callee_id` ON `call_sessions`(`callee_id`);
CREATE UNIQUE INDEX `idx_call_sessions_call_id` ON `call_sessions`(`call_id`);
CREATE TABLE `user_blocks` (`id` integer PRIMARY KEY AUTOINCREMENT,`blocker_id` integer NOT NULL,`blocked_user_id` integer NOT NULL,`created_at` datetime);
CREATE INDEX `idx_user_blocks_blocked_user_id` ON `user_blocks`(`blocked_user_id`);
CREATE UNIQUE INDEX `idx_block_pair` ON `user_blocks`(`blocker_id`,`blocked_user_id`);
CREATE INDEX `idx_user_blocks_blocker_id` ON `user_blocks`(`blocker_id`);
CREATE TABLE `abuse_reports` (`id` integer PRIMARY KEY AUTOINCREMENT,`reporter_id` integer NOT NULL,`reported_user_id` integer NOT NULL,`category` text NOT NULL,`details` text,`status` text NOT NULL DEFAULT "open",`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_abuse_reports_category` ON `abuse_reports`(`category`);
CREATE INDEX `idx_abuse_reports_reported_user_id` ON `abuse_reports`(`reported_user_id`);
CREATE INDEX `idx_abuse_reports_reporter_id` ON `abuse_reports`(`reporter_id`);
CREATE INDEX `idx_abuse_reports_created_at` ON `abuse_reports`(`created_at`);
CREATE INDEX `idx_abuse_reports_status` ON `abuse_reports`(`status`);
CREATE TABLE `legal_acceptances` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer NOT NULL,`terms_version` text NOT NULL,`privacy_version` text NOT NULL,`accepted_at` datetime NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_legal_acceptances_accepted_at` ON `legal_acceptances`(`accepted_at`);
CREATE UNIQUE INDEX `idx_legal_acceptances_user_id` ON `legal_acceptances`(`user_id`);
CREATE TABLE `user_entitlements` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer NOT NULL,`entitlement` text NOT NULL,`tier` text NOT NULL,`product_id` text,`source` text NOT NULL DEFAULT "system",`status` text NOT NULL,`expires_at` datetime,`last_synced_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_user_entitlements_status` ON `user_entitlements`(`status`);
CREATE INDEX `idx_user_entitlements_product_id` ON `user_entitlements`(`product_id`);
CREATE INDEX `idx_user_entitlements_tier` ON `user_entitlements`(`tier`);
CREATE UNIQUE INDEX `idx_user_entitlement` ON `user_entitlements`(`user_id`,`entitlement`);
CREATE INDEX `idx_user_entitlements_user_id` ON `user_entitlements`(`user_id`);
CREATE INDEX `idx_user_entitlements_expires_at` ON `user_entitlements`(`expires_at`);
CREATE TABLE `usage_ledgers` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer NOT NULL,`feature` text NOT NULL,`period_key` text NOT NULL,`units` integer NOT NULL DEFAULT 0,`created_at` datetime,`updated_at` datetime);
CREATE UNIQUE INDEX `idx_usage_period` ON `usage_ledgers`(`user_id`,`feature`,`period_key`);
CREATE INDEX `idx_usage_ledgers_user_id` ON `usage_ledgers`(`user_id`);
CREATE TABLE `translation_usage_slices` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer NOT NULL,`call_id` text NOT NULL,`slice_index` integer NOT NULL,`event_timestamp_ms` integer NOT NULL,`duration_seconds` integer NOT NULL DEFAULT 30,`tier` text NOT NULL,`created_at` datetime);
CREATE INDEX `idx_translation_usage_slices_created_at` ON `translation_usage_slices`(`created_at`);
CREATE INDEX `idx_translation_usage_slices_call_id` ON `translation_usage_slices`(`call_id`);
CREATE UNIQUE INDEX `idx_translation_usage_slice` ON `translation_usage_slices`(`user_id`,`call_id`,`slice_index`);
CREATE INDEX `idx_translation_usage_slices_user_id` ON `translation_usage_slices`(`user_id`);
CREATE TABLE `billing_webhook_events` (`id` integer PRIMARY KEY AUTOINCREMENT,`event_id` text NOT NULL,`app_user_id` text,`event_type` text,`payload_json` longtext NOT NULL,`processed_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_billing_webhook_events_created_at` ON `billing_webhook_events`(`created_at`);
CREATE INDEX `idx_billing_webhook_events_processed_at` ON `billing_webhook_events`(`processed_at`);
CREATE INDEX `idx_billing_webhook_events_event_type` ON `billing_webhook_events`(`event_type`);
CREATE INDEX `idx_billing_webhook_events_app_user_id` ON `billing_webhook_events`(`app_user_id`);
CREATE UNIQUE INDEX `idx_billing_webhook_events_event_id` ON `billing_webhook_events`(`event_id`);
CREATE TABLE `deletion_audits` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer NOT NULL,`deleted_at` datetime NOT NULL,`contacts_deleted` integer NOT NULL DEFAULT 0,`calls_deleted` integer NOT NULL DEFAULT 0,`blocks_deleted` integer NOT NULL DEFAULT 0,`reports_deleted` integer NOT NULL DEFAULT 0,`legal_records_deleted` integer NOT NULL DEFAULT 0,`usage_rows_deleted` integer NOT NULL DEFAULT 0,`entitlements_deleted` integer NOT NULL DEFAULT 0,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_deletion_audits_deleted_at` ON `deletion_audits`(`deleted_at`);
CREATE INDEX `idx_deletion_audits_user_id` ON `deletion_audits`(`user_id`);
CREATE TABLE `invitations` (`id` integer PRIMARY KEY AUTOINCREMENT,`code` text NOT NULL,`inviter_id` integer NOT NULL,`inviter_email` text NOT NULL,`inviter_display_name` text,`target_email` text NOT NULL,`default_source_lang` text NOT NULL,`default_target_lang` text NOT NULL,`note` text,`status` text NOT NULL DEFAULT "pending",`accepted_user_id` integer,`accepted_at` datetime,`expires_at` datetime NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_invitations_accepted_at` ON `invitations`(`accepted_at`);
CREATE INDEX `idx_invitations_accepted_user_id` ON `invitations`(`accepted_user_id`);
CREATE INDEX `idx_invitations_status` ON `invitations`(`status`);
CREATE INDEX `idx_invitations_target_email` ON `invitations`(`target_email`);
CREATE INDEX `idx_invitations_inviter_email` ON `invitations`(`inviter_email`);
CREATE INDEX `idx_invitations_inviter_id` ON `invitations`(`inviter_id`);
CREATE INDEX `idx_invitations_created_at` ON `invitations`(`created_at`);
CREATE INDEX `idx_invitations_expires_at` ON `invitations`(`expires_at`);
CREATE UNIQUE INDEX `idx_invitations_code` ON `invitations`(`code`);
CREATE TABLE `contact_profiles` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL DEFAULT 0,`owner_id` integer NOT NULL,`contact_user_id` integer NOT NULL,`company` text,`role` text,`timezone` text,`default_source_lang` text,`default_target_lang` text,`relationship_status` text NOT NULL DEFAULT "new",`preferred_contact_start` text,`preferred_contact_end` text,`preferred_contact_days` text,`last_followup_state` text,`note` text,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_contact_profiles_organization_id` ON `contact_profiles`(`organization_id`);
CREATE INDEX `idx_contact_profiles_contact_user_id` ON `contact_profiles`(`contact_user_id`);
CREATE INDEX `idx_contact_profiles_owner_id` ON `contact_profiles`(`owner_id`);
CREATE UNIQUE INDEX `idx_contact_profile_org_owner_contact` ON `contact_profiles`(`organization_id`,`owner_id`,`contact_user_id`);
CREATE TABLE `call_transcript_segments` (`id` integer PRIMARY KEY AUTOINCREMENT,`call_id` text NOT NULL,`user_id` integer NOT NULL,`peer_user_id` integer NOT NULL,`from_email` text NOT NULL,`to_email` text NOT NULL,`original_text` text NOT NULL,`translated_text` text,`source_lang` text,`target_lang` text,`timestamp_ms` integer NOT NULL,`created_at` datetime);
CREATE INDEX `idx_call_transcript_segments_timestamp_ms` ON `call_transcript_segments`(`timestamp_ms`);
CREATE INDEX `idx_call_transcript_segments_to_email` ON `call_transcript_segments`(`to_email`);
CREATE INDEX `idx_call_transcript_segments_from_email` ON `call_transcript_segments`(`from_email`);
CREATE INDEX `idx_call_transcript_segments_peer_user_id` ON `call_transcript_segments`(`peer_user_id`);
CREATE INDEX `idx_call_transcript_segments_user_id` ON `call_transcript_segments`(`user_id`);
CREATE INDEX `idx_call_transcript_segments_call_id` ON `call_transcript_segments`(`call_id`);
CREATE INDEX `idx_call_transcript_segments_created_at` ON `call_transcript_segments`(`created_at`);
CREATE TABLE `call_followups` (`id` integer PRIMARY KEY AUTOINCREMENT,`call_id` text NOT NULL,`organization_id` integer NOT NULL DEFAULT 0,`user_id` integer NOT NULL,`peer_user_id` integer NOT NULL,`deal_id` integer,`status` text NOT NULL DEFAULT "pending",`source` text NOT NULL DEFAULT "metadata",`summary_cn` text,`summary_en` text,`key_points_json` longtext,`action_items_json` longtext,`next_step` text,`risk_flags_json` longtext,`followup_draft_cn` text,`followup_draft_en` text,`generated_at` datetime,`transcript_count` integer NOT NULL DEFAULT 0,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_call_followups_user_id` ON `call_followups`(`user_id`);
CREATE INDEX `idx_call_followups_organization_id` ON `call_followups`(`organization_id`);
CREATE UNIQUE INDEX `idx_call_followups_call_id` ON `call_followups`(`call_id`);
CREATE INDEX `idx_call_followups_generated_at` ON `call_followups`(`generated_at`);
CREATE INDEX `idx_call_followups_status` ON `call_followups`(`status`);
CREATE INDEX `idx_call_followups_deal_id` ON `call_followups`(`deal_id`);
CREATE INDEX `idx_call_followups_peer_user_id` ON `call_followups`(`peer_user_id`);
CREATE TABLE `follow_up_tasks` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL DEFAULT 0,`user_id` integer NOT NULL,`peer_user_id` integer NOT NULL,`call_id` text,`deal_id` integer,`type` text NOT NULL,`status` text NOT NULL DEFAULT "open",`title` text NOT NULL,`description` text,`due_at` datetime,`completed_at` datetime,`last_reminder_at` datetime,`reminder_mode` text,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_follow_up_tasks_created_at` ON `follow_up_tasks`(`created_at`);
CREATE INDEX `idx_follow_up_tasks_last_reminder_at` ON `follow_up_tasks`(`last_reminder_at`);
CREATE INDEX `idx_follow_up_tasks_due_at` ON `follow_up_tasks`(`due_at`);
CREATE INDEX `idx_follow_up_tasks_type` ON `follow_up_tasks`(`type`);
CREATE INDEX `idx_follow_up_tasks_peer_user_id` ON `follow_up_tasks`(`peer_user_id`);
CREATE INDEX `idx_follow_up_tasks_completed_at` ON `follow_up_tasks`(`completed_at`);
CREATE INDEX `idx_follow_up_tasks_status` ON `follow_up_tasks`(`status`);
CREATE INDEX `idx_follow_up_tasks_deal_id` ON `follow_up_tasks`(`deal_id`);
CREATE INDEX `idx_follow_up_tasks_call_id` ON `follow_up_tasks`(`call_id`);
CREATE INDEX `idx_follow_up_tasks_user_id` ON `follow_up_tasks`(`user_id`);
CREATE INDEX `idx_follow_up_tasks_organization_id` ON `follow_up_tasks`(`organization_id`);
CREATE TABLE `organizations` (`id` integer PRIMARY KEY AUTOINCREMENT,`name` text NOT NULL,`slug` text NOT NULL,`description` text,`created_by` integer NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_organizations_created_by` ON `organizations`(`created_by`);
CREATE UNIQUE INDEX `idx_organizations_slug` ON `organizations`(`slug`);
CREATE TABLE `organization_members` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`user_id` integer NOT NULL,`role` text NOT NULL,`joined_at` datetime NOT NULL,`last_active_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_organization_members_last_active_at` ON `organization_members`(`last_active_at`);
CREATE INDEX `idx_organization_members_joined_at` ON `organization_members`(`joined_at`);
CREATE INDEX `idx_organization_members_role` ON `organization_members`(`role`);
CREATE INDEX `idx_organization_members_user_id` ON `organization_members`(`user_id`);
CREATE UNIQUE INDEX `idx_org_member` ON `organization_members`(`organization_id`,`user_id`);
CREATE INDEX `idx_organization_members_organization_id` ON `organization_members`(`organization_id`);
CREATE TABLE `teams` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`name` text NOT NULL,`slug` text NOT NULL,`description` text,`created_by` integer NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_teams_created_by` ON `teams`(`created_by`);
CREATE INDEX `idx_teams_organization_id` ON `teams`(`organization_id`);
CREATE TABLE `team_members` (`id` integer PRIMARY KEY AUTOINCREMENT,`team_id` integer NOT NULL,`user_id` integer NOT NULL,`role` text NOT NULL,`joined_at` datetime NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_team_members_joined_at` ON `team_members`(`joined_at`);
CREATE INDEX `idx_team_members_role` ON `team_members`(`role`);
CREATE INDEX `idx_team_members_user_id` ON `team_members`(`user_id`);
CREATE UNIQUE INDEX `idx_team_member` ON `team_members`(`team_id`,`user_id`);
CREATE INDEX `idx_team_members_team_id` ON `team_members`(`team_id`);
CREATE TABLE `organization_invites` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`team_id` integer,`code` text NOT NULL,`inviter_id` integer NOT NULL,`target_email` text NOT NULL,`role` text NOT NULL DEFAULT "member",`status` text NOT NULL DEFAULT "pending",`accepted_user_id` integer,`accepted_at` datetime,`expires_at` datetime NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_organization_invites_status` ON `organization_invites`(`status`);
CREATE INDEX `idx_organization_invites_team_id` ON `organization_invites`(`team_id`);
CREATE INDEX `idx_organization_invites_organization_id` ON `organization_invites`(`organization_id`);
CREATE INDEX `idx_organization_invites_expires_at` ON `organization_invites`(`expires_at`);
CREATE INDEX `idx_organization_invites_accepted_at` ON `organization_invites`(`accepted_at`);
CREATE INDEX `idx_organization_invites_accepted_user_id` ON `organization_invites`(`accepted_user_id`);
CREATE INDEX `idx_organization_invites_target_email` ON `organization_invites`(`target_email`);
CREATE INDEX `idx_organization_invites_inviter_id` ON `organization_invites`(`inviter_id`);
CREATE UNIQUE INDEX `idx_organization_invites_code` ON `organization_invites`(`code`);
CREATE TABLE `organization_policies` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`recording_mode` text NOT NULL DEFAULT "off",`recording_storage_days` integer NOT NULL DEFAULT 30,`recording_export_allowed` numeric NOT NULL DEFAULT false,`created_at` datetime,`updated_at` datetime);
CREATE UNIQUE INDEX `idx_organization_policies_organization_id` ON `organization_policies`(`organization_id`);
CREATE TABLE `conversations` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`team_id` integer,`room_id` integer,`type` text NOT NULL,`title` text,`topic` text,`status` text NOT NULL DEFAULT "open",`assignee_user_id` integer,`priority` text NOT NULL DEFAULT "normal",`contact_id` integer,`last_internal_note_at` datetime,`created_by` integer NOT NULL,`last_message_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_conversations_room_id` ON `conversations`(`room_id`);
CREATE INDEX `idx_conversations_team_id` ON `conversations`(`team_id`);
CREATE INDEX `idx_conversations_organization_id` ON `conversations`(`organization_id`);
CREATE INDEX `idx_conversations_last_message_at` ON `conversations`(`last_message_at`);
CREATE INDEX `idx_conversations_created_by` ON `conversations`(`created_by`);
CREATE INDEX `idx_conversations_last_internal_note_at` ON `conversations`(`last_internal_note_at`);
CREATE INDEX `idx_conversations_contact_id` ON `conversations`(`contact_id`);
CREATE INDEX `idx_conversations_priority` ON `conversations`(`priority`);
CREATE INDEX `idx_conversations_assignee_user_id` ON `conversations`(`assignee_user_id`);
CREATE INDEX `idx_conversations_status` ON `conversations`(`status`);
CREATE INDEX `idx_conversations_type` ON `conversations`(`type`);
CREATE TABLE `conversation_notes` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer NOT NULL,`author_id` integer NOT NULL,`body` text NOT NULL,`created_at` datetime);
CREATE INDEX `idx_conversation_notes_conversation_id` ON `conversation_notes`(`conversation_id`);
CREATE INDEX `idx_conversation_notes_organization_id` ON `conversation_notes`(`organization_id`);
CREATE INDEX `idx_conversation_notes_created_at` ON `conversation_notes`(`created_at`);
CREATE INDEX `idx_conversation_notes_author_id` ON `conversation_notes`(`author_id`);
CREATE TABLE `conversation_members` (`id` integer PRIMARY KEY AUTOINCREMENT,`conversation_id` integer NOT NULL,`user_id` integer NOT NULL,`role` text NOT NULL DEFAULT "member",`last_read_at` datetime,`muted_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE UNIQUE INDEX `idx_conversation_member` ON `conversation_members`(`conversation_id`,`user_id`);
CREATE INDEX `idx_conversation_members_conversation_id` ON `conversation_members`(`conversation_id`);
CREATE INDEX `idx_conversation_members_muted_at` ON `conversation_members`(`muted_at`);
CREATE INDEX `idx_conversation_members_last_read_at` ON `conversation_members`(`last_read_at`);
CREATE INDEX `idx_conversation_members_user_id` ON `conversation_members`(`user_id`);
CREATE TABLE `messages` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer NOT NULL,`sender_id` integer NOT NULL,`reply_to_message_id` integer,`type` text NOT NULL,`body` text,`metadata_json` longtext,`edited_at` datetime,`deleted_at` datetime,`deleted_by` integer,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_messages_created_at` ON `messages`(`created_at`);
CREATE INDEX `idx_messages_deleted_at` ON `messages`(`deleted_at`);
CREATE INDEX `idx_messages_edited_at` ON `messages`(`edited_at`);
CREATE INDEX `idx_messages_type` ON `messages`(`type`);
CREATE INDEX `idx_messages_sender_id` ON `messages`(`sender_id`);
CREATE INDEX `idx_messages_deleted_by` ON `messages`(`deleted_by`);
CREATE INDEX `idx_messages_reply_to_message_id` ON `messages`(`reply_to_message_id`);
CREATE INDEX `idx_messages_conversation_id` ON `messages`(`conversation_id`);
CREATE INDEX `idx_messages_organization_id` ON `messages`(`organization_id`);
CREATE TABLE `message_reads` (`id` integer PRIMARY KEY AUTOINCREMENT,`message_id` integer NOT NULL,`user_id` integer NOT NULL,`read_at` datetime NOT NULL,`created_at` datetime);
CREATE UNIQUE INDEX `idx_message_read` ON `message_reads`(`message_id`,`user_id`);
CREATE INDEX `idx_message_reads_message_id` ON `message_reads`(`message_id`);
CREATE INDEX `idx_message_reads_read_at` ON `message_reads`(`read_at`);
CREATE INDEX `idx_message_reads_user_id` ON `message_reads`(`user_id`);
CREATE TABLE `chat_events` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`user_id` integer NOT NULL,`sequence` integer NOT NULL DEFAULT 0,`event` text NOT NULL,`dedup_key` text,`payload_json` longtext,`created_at` datetime);
CREATE UNIQUE INDEX `idx_chat_events_dedup_key` ON `chat_events`(`dedup_key`);
CREATE INDEX `idx_chat_events_event` ON `chat_events`(`event`);
CREATE INDEX `idx_chat_events_sequence` ON `chat_events`(`sequence`);
CREATE INDEX `idx_chat_event_recipient` ON `chat_events`(`organization_id`,`user_id`,`created_at`);
CREATE TABLE `attachments` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer NOT NULL,`message_id` integer,`uploader_id` integer NOT NULL,`storage_driver` text NOT NULL DEFAULT "local",`storage_bucket` text,`file_name` text NOT NULL,`content_type` text,`object_key` text,`file_size` integer NOT NULL DEFAULT 0,`created_at` datetime);
CREATE INDEX `idx_attachments_conversation_id` ON `attachments`(`conversation_id`);
CREATE INDEX `idx_attachments_organization_id` ON `attachments`(`organization_id`);
CREATE INDEX `idx_attachments_uploader_id` ON `attachments`(`uploader_id`);
CREATE INDEX `idx_attachments_message_id` ON `attachments`(`message_id`);
CREATE TABLE `message_reactions` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer NOT NULL,`message_id` integer NOT NULL,`user_id` integer NOT NULL,`emoji` text NOT NULL,`created_at` datetime);
CREATE INDEX `idx_message_reactions_conversation_id` ON `message_reactions`(`conversation_id`);
CREATE INDEX `idx_message_reactions_organization_id` ON `message_reactions`(`organization_id`);
CREATE INDEX `idx_message_reactions_user_id` ON `message_reactions`(`user_id`);
CREATE UNIQUE INDEX `idx_message_reaction` ON `message_reactions`(`message_id`,`user_id`,`emoji`);
CREATE INDEX `idx_message_reactions_message_id` ON `message_reactions`(`message_id`);
CREATE TABLE `conversation_pins` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer NOT NULL,`message_id` integer NOT NULL,`pinned_by` integer NOT NULL,`created_at` datetime);
CREATE INDEX `idx_conversation_pins_created_at` ON `conversation_pins`(`created_at`);
CREATE INDEX `idx_conversation_pins_pinned_by` ON `conversation_pins`(`pinned_by`);
CREATE INDEX `idx_conversation_pins_message_id` ON `conversation_pins`(`message_id`);
CREATE UNIQUE INDEX `idx_conversation_pin` ON `conversation_pins`(`conversation_id`,`message_id`);
CREATE INDEX `idx_conversation_pins_conversation_id` ON `conversation_pins`(`conversation_id`);
CREATE INDEX `idx_conversation_pins_organization_id` ON `conversation_pins`(`organization_id`);
CREATE TABLE `organization_audit_events` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`actor_user_id` integer NOT NULL,`action` text NOT NULL,`target_type` text NOT NULL,`target_id` text NOT NULL,`metadata_json` longtext,`created_at` datetime);
CREATE INDEX `idx_organization_audit_events_actor_user_id` ON `organization_audit_events`(`actor_user_id`);
CREATE INDEX `idx_organization_audit_events_organization_id` ON `organization_audit_events`(`organization_id`);
CREATE INDEX `idx_organization_audit_events_created_at` ON `organization_audit_events`(`created_at`);
CREATE INDEX `idx_organization_audit_events_target_id` ON `organization_audit_events`(`target_id`);
CREATE INDEX `idx_organization_audit_events_target_type` ON `organization_audit_events`(`target_type`);
CREATE INDEX `idx_organization_audit_events_action` ON `organization_audit_events`(`action`);
CREATE TABLE `push_devices` (`id` integer PRIMARY KEY AUTOINCREMENT,`user_id` integer NOT NULL,`provider` text NOT NULL DEFAULT "fcm",`platform` text NOT NULL DEFAULT "android",`device_name` text,`app_version` text,`token` text NOT NULL,`last_registered` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_push_devices_platform` ON `push_devices`(`platform`);
CREATE INDEX `idx_push_devices_provider` ON `push_devices`(`provider`);
CREATE UNIQUE INDEX `idx_push_device_user_token` ON `push_devices`(`user_id`,`token`);
CREATE INDEX `idx_push_devices_user_id` ON `push_devices`(`user_id`);
CREATE TABLE `call_rooms` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`team_id` integer,`conversation_id` integer,`title` text NOT NULL,`status` text NOT NULL,`created_by` integer NOT NULL,`started_at` datetime,`ended_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_call_rooms_status` ON `call_rooms`(`status`);
CREATE INDEX `idx_call_rooms_conversation_id` ON `call_rooms`(`conversation_id`);
CREATE INDEX `idx_call_rooms_team_id` ON `call_rooms`(`team_id`);
CREATE INDEX `idx_call_rooms_organization_id` ON `call_rooms`(`organization_id`);
CREATE INDEX `idx_call_rooms_ended_at` ON `call_rooms`(`ended_at`);
CREATE INDEX `idx_call_rooms_started_at` ON `call_rooms`(`started_at`);
CREATE INDEX `idx_call_rooms_created_by` ON `call_rooms`(`created_by`);
CREATE TABLE `call_room_members` (`id` integer PRIMARY KEY AUTOINCREMENT,`room_id` integer NOT NULL,`user_id` integer NOT NULL,`role` text NOT NULL DEFAULT "member",`joined_at` datetime,`left_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_call_room_members_left_at` ON `call_room_members`(`left_at`);
CREATE INDEX `idx_call_room_members_joined_at` ON `call_room_members`(`joined_at`);
CREATE INDEX `idx_call_room_members_user_id` ON `call_room_members`(`user_id`);
CREATE UNIQUE INDEX `idx_room_member` ON `call_room_members`(`room_id`,`user_id`);
CREATE INDEX `idx_call_room_members_room_id` ON `call_room_members`(`room_id`);
CREATE TABLE `call_room_events` (`id` integer PRIMARY KEY AUTOINCREMENT,`room_id` integer NOT NULL,`user_id` integer NOT NULL,`type` text NOT NULL,`payload_json` longtext,`created_at` datetime);
CREATE INDEX `idx_call_room_events_created_at` ON `call_room_events`(`created_at`);
CREATE INDEX `idx_call_room_events_type` ON `call_room_events`(`type`);
CREATE INDEX `idx_call_room_events_user_id` ON `call_room_events`(`user_id`);
CREATE INDEX `idx_call_room_events_room_id` ON `call_room_events`(`room_id`);
CREATE TABLE `recording_sessions` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`room_id` integer NOT NULL,`started_by` integer NOT NULL,`status` text NOT NULL,`started_at` datetime,`stopped_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_recording_sessions_organization_id` ON `recording_sessions`(`organization_id`);
CREATE INDEX `idx_recording_sessions_stopped_at` ON `recording_sessions`(`stopped_at`);
CREATE INDEX `idx_recording_sessions_started_at` ON `recording_sessions`(`started_at`);
CREATE INDEX `idx_recording_sessions_status` ON `recording_sessions`(`status`);
CREATE INDEX `idx_recording_sessions_started_by` ON `recording_sessions`(`started_by`);
CREATE INDEX `idx_recording_sessions_room_id` ON `recording_sessions`(`room_id`);
CREATE TABLE `recording_files` (`id` integer PRIMARY KEY AUTOINCREMENT,`recording_session_id` integer NOT NULL,`storage_driver` text NOT NULL DEFAULT "local",`storage_bucket` text,`object_key` text,`e_tag` text,`content_type` text,`file_size_bytes` integer NOT NULL DEFAULT 0,`duration_seconds` integer NOT NULL DEFAULT 0,`metadata_json` longtext,`retention_until` datetime,`deleted_at` datetime,`created_at` datetime);
CREATE INDEX `idx_recording_files_deleted_at` ON `recording_files`(`deleted_at`);
CREATE INDEX `idx_recording_files_retention_until` ON `recording_files`(`retention_until`);
CREATE INDEX `idx_recording_files_recording_session_id` ON `recording_files`(`recording_session_id`);
CREATE TABLE `recording_transcriptions` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer,`room_id` integer NOT NULL,`recording_session_id` integer NOT NULL,`status` text NOT NULL,`provider` text,`segment_count` integer NOT NULL DEFAULT 0,`error_message` text,`started_at` datetime,`completed_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_recording_transcriptions_status` ON `recording_transcriptions`(`status`);
CREATE UNIQUE INDEX `idx_recording_transcriptions_recording_session_id` ON `recording_transcriptions`(`recording_session_id`);
CREATE INDEX `idx_recording_transcriptions_room_id` ON `recording_transcriptions`(`room_id`);
CREATE INDEX `idx_recording_transcriptions_conversation_id` ON `recording_transcriptions`(`conversation_id`);
CREATE INDEX `idx_recording_transcriptions_organization_id` ON `recording_transcriptions`(`organization_id`);
CREATE INDEX `idx_recording_transcriptions_completed_at` ON `recording_transcriptions`(`completed_at`);
CREATE INDEX `idx_recording_transcriptions_started_at` ON `recording_transcriptions`(`started_at`);
CREATE TABLE `meeting_transcript_segments` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer NOT NULL,`room_id` integer NOT NULL,`recording_session_id` integer NOT NULL,`recording_file_id` integer NOT NULL,`speaker_user_id` integer,`track_key` text,`source` text NOT NULL,`provider` text,`language` text,`text` text NOT NULL,`start_ms` integer NOT NULL DEFAULT 0,`end_ms` integer NOT NULL DEFAULT 0,`confidence` real NOT NULL DEFAULT 0,`created_at` datetime);
CREATE INDEX `idx_meeting_transcript_segments_created_at` ON `meeting_transcript_segments`(`created_at`);
CREATE INDEX `idx_meeting_transcript_segments_room_id` ON `meeting_transcript_segments`(`room_id`);
CREATE INDEX `idx_meeting_transcript_segments_source` ON `meeting_transcript_segments`(`source`);
CREATE INDEX `idx_meeting_transcript_segments_track_key` ON `meeting_transcript_segments`(`track_key`);
CREATE INDEX `idx_meeting_transcript_segments_speaker_user_id` ON `meeting_transcript_segments`(`speaker_user_id`);
CREATE INDEX `idx_meeting_transcript_segments_recording_file_id` ON `meeting_transcript_segments`(`recording_file_id`);
CREATE INDEX `idx_meeting_transcript_segments_recording_session_id` ON `meeting_transcript_segments`(`recording_session_id`);
CREATE INDEX `idx_meeting_transcript_segments_conversation_id` ON `meeting_transcript_segments`(`conversation_id`);
CREATE INDEX `idx_meeting_transcript_segments_organization_id` ON `meeting_transcript_segments`(`organization_id`);
CREATE TABLE `recording_consents` (`id` integer PRIMARY KEY AUTOINCREMENT,`recording_session_id` integer NOT NULL,`user_id` integer NOT NULL,`consent_status` text NOT NULL,`recorded_at` datetime NOT NULL,`created_at` datetime);
CREATE INDEX `idx_recording_consents_recorded_at` ON `recording_consents`(`recorded_at`);
CREATE INDEX `idx_recording_consents_user_id` ON `recording_consents`(`user_id`);
CREATE UNIQUE INDEX `idx_recording_consent` ON `recording_consents`(`recording_session_id`,`user_id`);
CREATE INDEX `idx_recording_consents_recording_session_id` ON `recording_consents`(`recording_session_id`);
CREATE TABLE `recording_exports` (`id` integer PRIMARY KEY AUTOINCREMENT,`recording_session_id` integer NOT NULL,`requested_by` integer NOT NULL,`reason` text,`status` text NOT NULL,`expires_at` datetime,`download_count` integer NOT NULL DEFAULT 0,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_recording_exports_status` ON `recording_exports`(`status`);
CREATE INDEX `idx_recording_exports_requested_by` ON `recording_exports`(`requested_by`);
CREATE INDEX `idx_recording_exports_recording_session_id` ON `recording_exports`(`recording_session_id`);
CREATE INDEX `idx_recording_exports_expires_at` ON `recording_exports`(`expires_at`);
CREATE TABLE `room_settlements` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`room_id` integer NOT NULL,`user_id` integer NOT NULL,`duration_seconds` integer NOT NULL DEFAULT 0,`participant_count` integer NOT NULL DEFAULT 0,`bytes_sent` integer NOT NULL DEFAULT 0,`bytes_received` integer NOT NULL DEFAULT 0,`source_event_id` text NOT NULL,`status` text NOT NULL DEFAULT "applied",`occurred_at` datetime NOT NULL,`processed_at` datetime NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_room_settlements_room_id` ON `room_settlements`(`room_id`);
CREATE INDEX `idx_room_settlements_organization_id` ON `room_settlements`(`organization_id`);
CREATE INDEX `idx_room_settlements_processed_at` ON `room_settlements`(`processed_at`);
CREATE INDEX `idx_room_settlements_occurred_at` ON `room_settlements`(`occurred_at`);
CREATE INDEX `idx_room_settlements_status` ON `room_settlements`(`status`);
CREATE UNIQUE INDEX `idx_room_settlements_source_event_id` ON `room_settlements`(`source_event_id`);
CREATE INDEX `idx_room_settlements_user_id` ON `room_settlements`(`user_id`);
CREATE UNIQUE INDEX `idx_room_settlement_user` ON `room_settlements`(`room_id`,`user_id`);
CREATE TABLE `pipelines` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`name` text NOT NULL,`is_default` numeric NOT NULL DEFAULT false,`created_by` integer NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_pipelines_created_by` ON `pipelines`(`created_by`);
CREATE INDEX `idx_pipelines_organization_id` ON `pipelines`(`organization_id`);
CREATE TABLE `pipeline_stages` (`id` integer PRIMARY KEY AUTOINCREMENT,`pipeline_id` integer NOT NULL,`name` text NOT NULL,`position` integer NOT NULL DEFAULT 0,`is_closed` numeric NOT NULL DEFAULT false,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_pipeline_stages_pipeline_id` ON `pipeline_stages`(`pipeline_id`);
CREATE TABLE `deals` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`pipeline_id` integer NOT NULL,`stage_id` integer,`owner_id` integer NOT NULL,`title` text NOT NULL,`description` text,`status` text NOT NULL DEFAULT "open",`value_cents` integer NOT NULL DEFAULT 0,`currency` text NOT NULL DEFAULT "USD",`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_deals_status` ON `deals`(`status`);
CREATE INDEX `idx_deals_owner_id` ON `deals`(`owner_id`);
CREATE INDEX `idx_deals_stage_id` ON `deals`(`stage_id`);
CREATE INDEX `idx_deals_pipeline_id` ON `deals`(`pipeline_id`);
CREATE INDEX `idx_deals_organization_id` ON `deals`(`organization_id`);
CREATE TABLE `deal_contacts` (`id` integer PRIMARY KEY AUTOINCREMENT,`deal_id` integer NOT NULL,`contact_id` integer NOT NULL,`created_at` datetime);
CREATE INDEX `idx_deal_contacts_contact_id` ON `deal_contacts`(`contact_id`);
CREATE UNIQUE INDEX `idx_deal_contact` ON `deal_contacts`(`deal_id`,`contact_id`);
CREATE INDEX `idx_deal_contacts_deal_id` ON `deal_contacts`(`deal_id`);
CREATE TABLE `deal_activities` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`deal_id` integer NOT NULL,`type` text NOT NULL,`reference_type` text NOT NULL,`reference_id` text NOT NULL,`summary` text NOT NULL,`metadata_json` longtext,`created_by` integer NOT NULL,`created_at` datetime);
CREATE INDEX `idx_deal_activities_deal_id` ON `deal_activities`(`deal_id`);
CREATE INDEX `idx_deal_activities_organization_id` ON `deal_activities`(`organization_id`);
CREATE INDEX `idx_deal_activities_created_at` ON `deal_activities`(`created_at`);
CREATE INDEX `idx_deal_activities_created_by` ON `deal_activities`(`created_by`);
CREATE INDEX `idx_deal_activities_type` ON `deal_activities`(`type`);
CREATE TABLE `agent_runs` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`user_id` integer NOT NULL,`conversation_id` integer NOT NULL,`idempotency_key` text,`request_id` text,`source` text NOT NULL,`role` text NOT NULL DEFAULT "primary",`status` text NOT NULL,`prompt_version` text,`tool_schema_version` text,`goal` text,`summary` text,`action_items_json` longtext,`next_step` text,`risk_flags_json` longtext,`error_message` text,`attempts` integer NOT NULL DEFAULT 0,`lease_until` datetime,`started_at` datetime,`completed_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_agent_runs_organization_id` ON `agent_runs`(`organization_id`);
CREATE INDEX `idx_agent_runs_completed_at` ON `agent_runs`(`completed_at`);
CREATE INDEX `idx_agent_runs_tool_schema_version` ON `agent_runs`(`tool_schema_version`);
CREATE INDEX `idx_agent_runs_status` ON `agent_runs`(`status`);
CREATE INDEX `idx_agent_runs_role` ON `agent_runs`(`role`);
CREATE INDEX `idx_agent_runs_source` ON `agent_runs`(`source`);
CREATE INDEX `idx_agent_runs_request_id` ON `agent_runs`(`request_id`);
CREATE INDEX `idx_agent_runs_idempotency_key` ON `agent_runs`(`idempotency_key`);
CREATE INDEX `idx_agent_runs_conversation_id` ON `agent_runs`(`conversation_id`);
CREATE INDEX `idx_agent_runs_started_at` ON `agent_runs`(`started_at`);
CREATE INDEX `idx_agent_runs_lease_until` ON `agent_runs`(`lease_until`);
CREATE INDEX `idx_agent_runs_prompt_version` ON `agent_runs`(`prompt_version`);
CREATE INDEX `idx_agent_runs_user_id` ON `agent_runs`(`user_id`);
CREATE TABLE `agent_steps` (`id` integer PRIMARY KEY AUTOINCREMENT,`run_id` integer NOT NULL,`name` text NOT NULL,`status` text NOT NULL,`input_json` longtext,`output_json` longtext,`error_message` text,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_agent_steps_status` ON `agent_steps`(`status`);
CREATE INDEX `idx_agent_steps_name` ON `agent_steps`(`name`);
CREATE INDEX `idx_agent_steps_run_id` ON `agent_steps`(`run_id`);
CREATE TABLE `agent_tool_calls` (`id` integer PRIMARY KEY AUTOINCREMENT,`run_id` integer NOT NULL,`step_id` integer,`call_id` text,`tool_name` text NOT NULL,`status` text NOT NULL,`tool_schema_version` text,`input_json` longtext,`output_json` longtext,`error_message` text,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_agent_tool_calls_tool_schema_version` ON `agent_tool_calls`(`tool_schema_version`);
CREATE INDEX `idx_agent_tool_calls_status` ON `agent_tool_calls`(`status`);
CREATE INDEX `idx_agent_tool_calls_tool_name` ON `agent_tool_calls`(`tool_name`);
CREATE INDEX `idx_agent_tool_calls_call_id` ON `agent_tool_calls`(`call_id`);
CREATE INDEX `idx_agent_tool_calls_step_id` ON `agent_tool_calls`(`step_id`);
CREATE INDEX `idx_agent_tool_calls_run_id` ON `agent_tool_calls`(`run_id`);
CREATE TABLE `agent_memories` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`user_id` integer NOT NULL,`conversation_id` integer NOT NULL,`scope` text NOT NULL,`key` text NOT NULL,`memory_type` text NOT NULL DEFAULT "summary",`importance` integer NOT NULL DEFAULT 0,`source_type` text,`source_ref_id` integer NOT NULL DEFAULT 0,`value_json` longtext NOT NULL,`last_run_id` integer NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_agent_memories_source_type` ON `agent_memories`(`source_type`);
CREATE INDEX `idx_agent_memories_user_id` ON `agent_memories`(`user_id`);
CREATE INDEX `idx_agent_memories_organization_id` ON `agent_memories`(`organization_id`);
CREATE INDEX `idx_agent_memories_source_ref_id` ON `agent_memories`(`source_ref_id`);
CREATE INDEX `idx_agent_memories_memory_type` ON `agent_memories`(`memory_type`);
CREATE INDEX `idx_agent_memories_scope` ON `agent_memories`(`scope`);
CREATE INDEX `idx_agent_memories_conversation_id` ON `agent_memories`(`conversation_id`);
CREATE UNIQUE INDEX `idx_agent_memory_key` ON `agent_memories`(`organization_id`,`user_id`,`conversation_id`,`key`);
CREATE INDEX `idx_agent_memories_last_run_id` ON `agent_memories`(`last_run_id`);
CREATE TABLE `agent_context_chunks` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer NOT NULL,`source_type` text NOT NULL,`source_id` integer NOT NULL,`content` longtext NOT NULL,`keywords` text,`last_run_id` integer NOT NULL DEFAULT 0,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_agent_context_chunks_last_run_id` ON `agent_context_chunks`(`last_run_id`);
CREATE INDEX `idx_agent_context_chunks_source_type` ON `agent_context_chunks`(`source_type`);
CREATE INDEX `idx_agent_context_chunks_conversation_id` ON `agent_context_chunks`(`conversation_id`);
CREATE UNIQUE INDEX `idx_agent_context_chunk_source` ON `agent_context_chunks`(`organization_id`,`conversation_id`,`source_type`,`source_id`);
CREATE INDEX `idx_agent_context_chunks_organization_id` ON `agent_context_chunks`(`organization_id`);
CREATE TABLE `agent_prompt_versions` (`id` integer PRIMARY KEY AUTOINCREMENT,`name` text NOT NULL,`version` text NOT NULL,`content_hash` text NOT NULL,`template` longtext NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_agent_prompt_versions_content_hash` ON `agent_prompt_versions`(`content_hash`);
CREATE INDEX `idx_agent_prompt_versions_version` ON `agent_prompt_versions`(`version`);
CREATE UNIQUE INDEX `idx_agent_prompt_version` ON `agent_prompt_versions`(`name`,`version`);
CREATE INDEX `idx_agent_prompt_versions_name` ON `agent_prompt_versions`(`name`);
CREATE INDEX `idx_agent_prompt_versions_created_at` ON `agent_prompt_versions`(`created_at`);
CREATE TABLE `tool_schema_versions` (`id` integer PRIMARY KEY AUTOINCREMENT,`name` text NOT NULL,`version` text NOT NULL,`schema_hash` text NOT NULL,`schema_json` longtext NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_tool_schema_versions_created_at` ON `tool_schema_versions`(`created_at`);
CREATE INDEX `idx_tool_schema_versions_schema_hash` ON `tool_schema_versions`(`schema_hash`);
CREATE INDEX `idx_tool_schema_versions_version` ON `tool_schema_versions`(`version`);
CREATE UNIQUE INDEX `idx_tool_schema_version` ON `tool_schema_versions`(`name`,`version`);
CREATE INDEX `idx_tool_schema_versions_name` ON `tool_schema_versions`(`name`);
CREATE TABLE `rag_source_groups` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`canonical_source_id` integer,`title` text NOT NULL,`status` text NOT NULL DEFAULT "active",`authority_score` real NOT NULL DEFAULT 0,`authority_label` text,`created_by` integer NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_rag_source_groups_created_at` ON `rag_source_groups`(`created_at`);
CREATE INDEX `idx_rag_source_groups_created_by` ON `rag_source_groups`(`created_by`);
CREATE INDEX `idx_rag_source_groups_status` ON `rag_source_groups`(`status`);
CREATE INDEX `idx_rag_source_groups_canonical_source_id` ON `rag_source_groups`(`canonical_source_id`);
CREATE INDEX `idx_rag_source_groups_organization_id` ON `rag_source_groups`(`organization_id`);
CREATE TABLE `rag_source_duplicates` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`source_group_id` integer,`source_id` integer NOT NULL,`candidate_source_id` integer NOT NULL,`duplicate_kind` text NOT NULL,`similarity` real NOT NULL DEFAULT 0,`status` text NOT NULL DEFAULT "pending",`decided_by` integer,`decision` text,`created_at` datetime,`updated_at` datetime,`decided_at` datetime);
CREATE INDEX `idx_rag_source_duplicates_duplicate_kind` ON `rag_source_duplicates`(`duplicate_kind`);
CREATE INDEX `idx_rag_source_duplicates_candidate_source_id` ON `rag_source_duplicates`(`candidate_source_id`);
CREATE INDEX `idx_rag_source_duplicates_organization_id` ON `rag_source_duplicates`(`organization_id`);
CREATE INDEX `idx_rag_source_duplicates_decided_by` ON `rag_source_duplicates`(`decided_by`);
CREATE INDEX `idx_rag_source_duplicates_status` ON `rag_source_duplicates`(`status`);
CREATE INDEX `idx_rag_source_duplicates_source_id` ON `rag_source_duplicates`(`source_id`);
CREATE INDEX `idx_rag_source_duplicates_source_group_id` ON `rag_source_duplicates`(`source_group_id`);
CREATE UNIQUE INDEX `idx_rag_duplicate_pair` ON `rag_source_duplicates`(`organization_id`,`source_id`,`candidate_source_id`);
CREATE INDEX `idx_rag_source_duplicates_decided_at` ON `rag_source_duplicates`(`decided_at`);
CREATE INDEX `idx_rag_source_duplicates_created_at` ON `rag_source_duplicates`(`created_at`);
CREATE TABLE `rag_sources` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer,`created_by` integer NOT NULL,`source_group_id` integer,`canonical_source_id` integer,`kind` text NOT NULL,`title` text NOT NULL,`uri` text,`file_name` text,`content_type` text,`authority_score` real NOT NULL DEFAULT 0,`authority_label` text,`dedupe_status` text NOT NULL DEFAULT "unique",`status` text NOT NULL DEFAULT "pending",`active_version_id` integer,`last_error` text,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_rag_sources_source_group_id` ON `rag_sources`(`source_group_id`);
CREATE INDEX `idx_rag_sources_created_by` ON `rag_sources`(`created_by`);
CREATE INDEX `idx_rag_sources_dedupe_status` ON `rag_sources`(`dedupe_status`);
CREATE INDEX `idx_rag_sources_kind` ON `rag_sources`(`kind`);
CREATE INDEX `idx_rag_sources_canonical_source_id` ON `rag_sources`(`canonical_source_id`);
CREATE INDEX `idx_rag_sources_conversation_id` ON `rag_sources`(`conversation_id`);
CREATE INDEX `idx_rag_sources_organization_id` ON `rag_sources`(`organization_id`);
CREATE INDEX `idx_rag_sources_created_at` ON `rag_sources`(`created_at`);
CREATE INDEX `idx_rag_sources_active_version_id` ON `rag_sources`(`active_version_id`);
CREATE INDEX `idx_rag_sources_status` ON `rag_sources`(`status`);
CREATE TABLE `rag_source_versions` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`source_id` integer NOT NULL,`version` integer NOT NULL,`content_hash` text NOT NULL,`normalized_hash` text,`sim_hash64` integer,`raw_text` longtext,`status` text NOT NULL DEFAULT "pending",`chunk_count` integer NOT NULL DEFAULT 0,`last_error` text,`created_at` datetime,`updated_at` datetime,`activated_at` datetime);
CREATE INDEX `idx_rag_source_versions_content_hash` ON `rag_source_versions`(`content_hash`);
CREATE INDEX `idx_rag_source_versions_source_id` ON `rag_source_versions`(`source_id`);
CREATE INDEX `idx_rag_source_versions_status` ON `rag_source_versions`(`status`);
CREATE INDEX `idx_rag_source_versions_normalized_hash` ON `rag_source_versions`(`normalized_hash`);
CREATE UNIQUE INDEX `idx_rag_source_version` ON `rag_source_versions`(`source_id`,`version`);
CREATE INDEX `idx_rag_source_versions_organization_id` ON `rag_source_versions`(`organization_id`);
CREATE INDEX `idx_rag_source_versions_activated_at` ON `rag_source_versions`(`activated_at`);
CREATE INDEX `idx_rag_source_versions_created_at` ON `rag_source_versions`(`created_at`);
CREATE INDEX `idx_rag_source_versions_sim_hash64` ON `rag_source_versions`(`sim_hash64`);
CREATE TABLE `rag_chunks` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`conversation_id` integer,`source_id` integer NOT NULL,`source_version_id` integer NOT NULL,`chunk_index` integer NOT NULL,`start_offset` integer NOT NULL DEFAULT 0,`end_offset` integer NOT NULL DEFAULT 0,`content_hash` text NOT NULL,`content` longtext NOT NULL,`keywords` text,`index_status` text NOT NULL DEFAULT "pending",`last_error` text,`indexed_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_rag_chunks_created_at` ON `rag_chunks`(`created_at`);
CREATE INDEX `idx_rag_chunks_indexed_at` ON `rag_chunks`(`indexed_at`);
CREATE INDEX `idx_rag_chunks_chunk_index` ON `rag_chunks`(`chunk_index`);
CREATE INDEX `idx_rag_chunks_source_version_id` ON `rag_chunks`(`source_version_id`);
CREATE INDEX `idx_rag_chunks_source_id` ON `rag_chunks`(`source_id`);
CREATE INDEX `idx_rag_chunks_index_status` ON `rag_chunks`(`index_status`);
CREATE INDEX `idx_rag_chunks_content_hash` ON `rag_chunks`(`content_hash`);
CREATE UNIQUE INDEX `idx_rag_chunk_version_hash` ON `rag_chunks`(`source_version_id`,`content_hash`);
CREATE INDEX `idx_rag_chunks_conversation_id` ON `rag_chunks`(`conversation_id`);
CREATE INDEX `idx_rag_chunks_organization_id` ON `rag_chunks`(`organization_id`);
CREATE TABLE `workflow_runs` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`user_id` integer NOT NULL,`conversation_id` integer NOT NULL,`agent_run_id` integer,`idempotency_key` text,`request_id` text,`status` text NOT NULL,`workflow_type` text NOT NULL DEFAULT "agent_lab",`workflow_version` text NOT NULL DEFAULT "agent_lab_v1",`preset` text,`prompt_version` text,`tool_schema_version` text,`state_json` longtext,`last_event_id` integer,`goal` text,`summary` text,`action_items_json` longtext,`next_step` text,`risk_flags_json` longtext,`citations_json` longtext,`error_message` text,`attempts` integer NOT NULL DEFAULT 0,`lease_until` datetime,`started_at` datetime,`completed_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_workflow_runs_completed_at` ON `workflow_runs`(`completed_at`);
CREATE INDEX `idx_workflow_runs_started_at` ON `workflow_runs`(`started_at`);
CREATE INDEX `idx_workflow_runs_status` ON `workflow_runs`(`status`);
CREATE INDEX `idx_workflow_runs_user_id` ON `workflow_runs`(`user_id`);
CREATE INDEX `idx_workflow_runs_workflow_version` ON `workflow_runs`(`workflow_version`);
CREATE INDEX `idx_workflow_runs_workflow_type` ON `workflow_runs`(`workflow_type`);
CREATE INDEX `idx_workflow_runs_idempotency_key` ON `workflow_runs`(`idempotency_key`);
CREATE INDEX `idx_workflow_runs_conversation_id` ON `workflow_runs`(`conversation_id`);
CREATE INDEX `idx_workflow_runs_organization_id` ON `workflow_runs`(`organization_id`);
CREATE INDEX `idx_workflow_runs_last_event_id` ON `workflow_runs`(`last_event_id`);
CREATE INDEX `idx_workflow_runs_tool_schema_version` ON `workflow_runs`(`tool_schema_version`);
CREATE INDEX `idx_workflow_runs_prompt_version` ON `workflow_runs`(`prompt_version`);
CREATE INDEX `idx_workflow_runs_request_id` ON `workflow_runs`(`request_id`);
CREATE INDEX `idx_workflow_runs_agent_run_id` ON `workflow_runs`(`agent_run_id`);
CREATE INDEX `idx_workflow_runs_created_at` ON `workflow_runs`(`created_at`);
CREATE INDEX `idx_workflow_runs_lease_until` ON `workflow_runs`(`lease_until`);
CREATE INDEX `idx_workflow_runs_preset` ON `workflow_runs`(`preset`);
CREATE TABLE `workflow_tasks` (`id` integer PRIMARY KEY AUTOINCREMENT,`workflow_run_id` integer NOT NULL,`organization_id` integer NOT NULL,`name` text NOT NULL,`role` text,`status` text NOT NULL,`depends_on_json` longtext,`input_json` longtext,`output_json` longtext,`error_message` text,`attempts` integer NOT NULL DEFAULT 0,`lease_until` datetime,`started_at` datetime,`completed_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_workflow_tasks_organization_id` ON `workflow_tasks`(`organization_id`);
CREATE INDEX `idx_workflow_tasks_created_at` ON `workflow_tasks`(`created_at`);
CREATE INDEX `idx_workflow_tasks_completed_at` ON `workflow_tasks`(`completed_at`);
CREATE INDEX `idx_workflow_tasks_name` ON `workflow_tasks`(`name`);
CREATE UNIQUE INDEX `idx_workflow_task_name` ON `workflow_tasks`(`workflow_run_id`,`name`);
CREATE INDEX `idx_workflow_tasks_workflow_run_id` ON `workflow_tasks`(`workflow_run_id`);
CREATE INDEX `idx_workflow_tasks_started_at` ON `workflow_tasks`(`started_at`);
CREATE INDEX `idx_workflow_tasks_lease_until` ON `workflow_tasks`(`lease_until`);
CREATE INDEX `idx_workflow_tasks_status` ON `workflow_tasks`(`status`);
CREATE INDEX `idx_workflow_tasks_role` ON `workflow_tasks`(`role`);
CREATE TABLE `workflow_history_events` (`id` integer PRIMARY KEY AUTOINCREMENT,`workflow_run_id` integer NOT NULL,`organization_id` integer NOT NULL,`event_type` text NOT NULL,`ref_type` text,`ref_id` integer,`attributes_json` longtext,`created_at` datetime);
CREATE INDEX `idx_workflow_history_events_ref_id` ON `workflow_history_events`(`ref_id`);
CREATE INDEX `idx_workflow_history_events_ref_type` ON `workflow_history_events`(`ref_type`);
CREATE INDEX `idx_workflow_history_events_event_type` ON `workflow_history_events`(`event_type`);
CREATE INDEX `idx_workflow_history_events_organization_id` ON `workflow_history_events`(`organization_id`);
CREATE INDEX `idx_workflow_history_events_workflow_run_id` ON `workflow_history_events`(`workflow_run_id`);
CREATE INDEX `idx_workflow_history_events_created_at` ON `workflow_history_events`(`created_at`);
CREATE TABLE `workflow_signals` (`id` integer PRIMARY KEY AUTOINCREMENT,`workflow_run_id` integer NOT NULL,`organization_id` integer NOT NULL,`signal_name` text NOT NULL,`payload_json` longtext,`status` text NOT NULL DEFAULT "received",`received_by` integer,`handled_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_workflow_signals_received_by` ON `workflow_signals`(`received_by`);
CREATE INDEX `idx_workflow_signals_status` ON `workflow_signals`(`status`);
CREATE INDEX `idx_workflow_signals_signal_name` ON `workflow_signals`(`signal_name`);
CREATE INDEX `idx_workflow_signals_organization_id` ON `workflow_signals`(`organization_id`);
CREATE INDEX `idx_workflow_signals_workflow_run_id` ON `workflow_signals`(`workflow_run_id`);
CREATE INDEX `idx_workflow_signals_created_at` ON `workflow_signals`(`created_at`);
CREATE INDEX `idx_workflow_signals_handled_at` ON `workflow_signals`(`handled_at`);
CREATE TABLE `workflow_timers` (`id` integer PRIMARY KEY AUTOINCREMENT,`workflow_run_id` integer NOT NULL,`organization_id` integer NOT NULL,`timer_name` text NOT NULL,`fire_at` datetime NOT NULL,`status` text NOT NULL DEFAULT "pending",`payload_json` longtext,`fired_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_workflow_timers_created_at` ON `workflow_timers`(`created_at`);
CREATE INDEX `idx_workflow_timers_fired_at` ON `workflow_timers`(`fired_at`);
CREATE INDEX `idx_workflow_timers_status` ON `workflow_timers`(`status`);
CREATE INDEX `idx_workflow_timers_fire_at` ON `workflow_timers`(`fire_at`);
CREATE INDEX `idx_workflow_timers_timer_name` ON `workflow_timers`(`timer_name`);
CREATE INDEX `idx_workflow_timers_organization_id` ON `workflow_timers`(`organization_id`);
CREATE INDEX `idx_workflow_timers_workflow_run_id` ON `workflow_timers`(`workflow_run_id`);
CREATE TABLE `agent_messages` (`id` integer PRIMARY KEY AUTOINCREMENT,`workflow_run_id` integer NOT NULL,`task_id` integer,`organization_id` integer NOT NULL,`from_role` text NOT NULL,`to_role` text NOT NULL,`message_type` text NOT NULL,`content_json` longtext NOT NULL,`correlation_id` text NOT NULL,`created_at` datetime);
CREATE INDEX `idx_agent_messages_task_id` ON `agent_messages`(`task_id`);
CREATE INDEX `idx_agent_messages_workflow_run_id` ON `agent_messages`(`workflow_run_id`);
CREATE INDEX `idx_agent_messages_created_at` ON `agent_messages`(`created_at`);
CREATE INDEX `idx_agent_messages_correlation_id` ON `agent_messages`(`correlation_id`);
CREATE INDEX `idx_agent_messages_message_type` ON `agent_messages`(`message_type`);
CREATE INDEX `idx_agent_messages_to_role` ON `agent_messages`(`to_role`);
CREATE INDEX `idx_agent_messages_from_role` ON `agent_messages`(`from_role`);
CREATE INDEX `idx_agent_messages_organization_id` ON `agent_messages`(`organization_id`);
CREATE TABLE `tool_policies` (`id` integer PRIMARY KEY AUTOINCREMENT,`organization_id` integer NOT NULL,`tool_name` text NOT NULL,`subject_role` text NOT NULL DEFAULT "member",`effect` text NOT NULL,`created_by` integer NOT NULL,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_tool_policies_created_at` ON `tool_policies`(`created_at`);
CREATE INDEX `idx_tool_policies_created_by` ON `tool_policies`(`created_by`);
CREATE INDEX `idx_tool_policies_effect` ON `tool_policies`(`effect`);
CREATE INDEX `idx_tool_policies_subject_role` ON `tool_policies`(`subject_role`);
CREATE INDEX `idx_tool_policies_tool_name` ON `tool_policies`(`tool_name`);
CREATE UNIQUE INDEX `idx_tool_policy` ON `tool_policies`(`organization_id`,`tool_name`,`subject_role`);
CREATE INDEX `idx_tool_policies_organization_id` ON `tool_policies`(`organization_id`);
CREATE TABLE `tool_approvals` (`id` integer PRIMARY KEY AUTOINCREMENT,`workflow_run_id` integer NOT NULL,`task_id` integer NOT NULL,`organization_id` integer NOT NULL,`tool_call_id` text NOT NULL,`tool_name` text NOT NULL,`status` text NOT NULL,`tool_schema_version` text,`input_json` longtext,`output_json` longtext,`error_message` text,`requested_by` integer NOT NULL,`decided_by` integer,`decision` text,`requested_at` datetime NOT NULL,`decided_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_tool_approvals_decided_at` ON `tool_approvals`(`decided_at`);
CREATE INDEX `idx_tool_approvals_decided_by` ON `tool_approvals`(`decided_by`);
CREATE INDEX `idx_tool_approvals_status` ON `tool_approvals`(`status`);
CREATE INDEX `idx_tool_approvals_organization_id` ON `tool_approvals`(`organization_id`);
CREATE INDEX `idx_tool_approvals_workflow_run_id` ON `tool_approvals`(`workflow_run_id`);
CREATE INDEX `idx_tool_approvals_created_at` ON `tool_approvals`(`created_at`);
CREATE INDEX `idx_tool_approvals_requested_at` ON `tool_approvals`(`requested_at`);
CREATE INDEX `idx_tool_approvals_requested_by` ON `tool_approvals`(`requested_by`);
CREATE INDEX `idx_tool_approvals_tool_schema_version` ON `tool_approvals`(`tool_schema_version`);
CREATE INDEX `idx_tool_approvals_tool_name` ON `tool_approvals`(`tool_name`);
CREATE UNIQUE INDEX `idx_tool_approval_call` ON `tool_approvals`(`tool_call_id`);
CREATE INDEX `idx_tool_approvals_tool_call_id` ON `tool_approvals`(`tool_call_id`);
CREATE INDEX `idx_tool_approvals_task_id` ON `tool_approvals`(`task_id`);
CREATE TABLE `event_outbox` (`id` integer PRIMARY KEY AUTOINCREMENT,`aggregate_type` text NOT NULL,`aggregate_id` integer NOT NULL,`event` text NOT NULL,`payload_json` longtext NOT NULL,`idempotency_key` text NOT NULL,`request_id` text,`status` text NOT NULL DEFAULT "pending",`attempts` integer NOT NULL DEFAULT 0,`locked_by` text,`locked_until` datetime,`last_error` text,`available_at` datetime,`published_at` datetime,`created_at` datetime,`updated_at` datetime);
CREATE INDEX `idx_event_outbox_status` ON `event_outbox`(`status`);
CREATE INDEX `idx_event_outbox_aggregate_id` ON `event_outbox`(`aggregate_id`);
CREATE INDEX `idx_event_outbox_aggregate_type` ON `event_outbox`(`aggregate_type`);
CREATE INDEX `idx_event_outbox_request_id` ON `event_outbox`(`request_id`);
CREATE UNIQUE INDEX `idx_event_outbox_idempotency_key` ON `event_outbox`(`idempotency_key`);
CREATE INDEX `idx_event_outbox_event` ON `event_outbox`(`event`);
CREATE INDEX `idx_event_outbox_created_at` ON `event_outbox`(`created_at`);
CREATE INDEX `idx_event_outbox_published_at` ON `event_outbox`(`published_at`);
CREATE INDEX `idx_event_outbox_available_at` ON `event_outbox`(`available_at`);
CREATE INDEX `idx_event_outbox_locked_until` ON `event_outbox`(`locked_until`);
CREATE INDEX `idx_event_outbox_locked_by` ON `event_outbox`(`locked_by`);
