import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  content: { padding: 16, paddingBottom: 48, width: "100%", maxWidth: 1120, alignSelf: "center" },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 },
  headerCopy: { flex: 1 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 8 },
  eyebrow: { fontSize: 12, color: "#64748b", textTransform: "uppercase" },
  title: { fontSize: 26, lineHeight: 34, fontWeight: "700", color: "#0f172a" },
  segmentedControl: { flexDirection: "row", borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 8, padding: 3, backgroundColor: "#fff", marginBottom: 16 },
  segment: { flex: 1, minHeight: 38, paddingHorizontal: 8, alignItems: "center", justifyContent: "center", borderRadius: 6 },
  segmentSelected: { backgroundColor: "#0f172a" },
  segmentText: { fontSize: 13, color: "#475569", fontWeight: "600" },
  segmentTextSelected: { color: "#fff" },
  notice: { borderLeftWidth: 3, borderLeftColor: "#2563eb", backgroundColor: "#eff6ff", color: "#1e40af", padding: 10, marginBottom: 14, lineHeight: 19 },
  sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 4, marginBottom: 12 },
  sectionTitle: { fontSize: 20, fontWeight: "700", color: "#0f172a" },
  sectionMeta: { fontSize: 12, lineHeight: 18, color: "#64748b" },
  formBand: { backgroundColor: "#fff", borderTopWidth: 1, borderBottomWidth: 1, borderColor: "#e2e8f0", paddingVertical: 16, paddingHorizontal: 14, marginHorizontal: -16, marginBottom: 16 },
  formTitle: { fontSize: 16, fontWeight: "700", color: "#1e293b", marginBottom: 10 },
  field: { marginBottom: 12 },
  fieldLabel: { fontSize: 13, fontWeight: "600", color: "#334155", marginBottom: 6 },
  input: { minHeight: 44, borderWidth: 1, borderColor: "#cbd5e1", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: "#fff", color: "#0f172a", fontSize: 15 },
  multilineInput: { minHeight: 88, textAlignVertical: "top" },
  inputError: { borderColor: "#dc2626" },
  errorText: { color: "#b91c1c", fontSize: 12, marginTop: 4 },
  warningText: { color: "#9a3412", backgroundColor: "#fff7ed", padding: 9, marginBottom: 10, lineHeight: 18 },
  actionButton: { minHeight: 42, borderRadius: 8, paddingHorizontal: 16, paddingVertical: 10, backgroundColor: "#2563eb", alignItems: "center", justifyContent: "center" },
  actionButtonCompact: { minHeight: 36, paddingHorizontal: 12, paddingVertical: 7 },
  actionButtonDanger: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#ef4444" },
  actionButtonDisabled: { opacity: 0.45 },
  actionButtonPressed: { opacity: 0.78 },
  actionButtonText: { color: "#fff", fontSize: 13, fontWeight: "700" },
  actionButtonDangerText: { color: "#b91c1c" },
  installationLayout: { gap: 14 },
  listPane: { gap: 8 },
  detailPane: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 8, padding: 14 },
  itemCard: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 8, padding: 14, marginBottom: 8 },
  itemCardSelected: { borderColor: "#2563eb", backgroundColor: "#eff6ff" },
  rowBetween: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", gap: 10 },
  flexCopy: { flex: 1, minWidth: 0 },
  itemTitle: { fontSize: 15, lineHeight: 21, fontWeight: "700", color: "#0f172a" },
  itemMeta: { fontSize: 12, lineHeight: 18, color: "#64748b", marginTop: 3 },
  detailTitle: { fontSize: 18, lineHeight: 24, fontWeight: "700", color: "#0f172a" },
  badge: { alignSelf: "flex-start", borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4 },
  badgeText: { fontSize: 11, fontWeight: "700" },
  detailGrid: { display: "flex", flexDirection: "row", flexWrap: "wrap", marginTop: 14, marginBottom: 10 },
  detailKey: { width: "22%", fontSize: 12, color: "#64748b", marginBottom: 7 },
  detailValue: { width: "28%", fontSize: 12, fontWeight: "600", color: "#1e293b", marginBottom: 7 },
  monospace: { fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 11, lineHeight: 17, color: "#475569", backgroundColor: "#f8fafc", padding: 8, marginBottom: 8 },
  actionRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 10 },
  divider: { height: 1, backgroundColor: "#e2e8f0", marginVertical: 18 },
  secretRow: { gap: 8, marginBottom: 4 },
  secretField: { flex: 1 },
  toolRow: { flexDirection: "row", alignItems: "flex-start", gap: 10, borderTopWidth: 1, borderTopColor: "#e2e8f0", paddingVertical: 12, paddingHorizontal: 8 },
  toolRowSelected: { backgroundColor: "#eff6ff" },
  toolName: { fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 12, lineHeight: 18, fontWeight: "600", color: "#0f172a" },
  toolDescription: { fontSize: 13, lineHeight: 19, color: "#475569", marginTop: 6 },
  approvalReason: { fontSize: 10, color: "#64748b", marginTop: 5, textAlign: "right" },
  approvalPolicy: { fontSize: 12, lineHeight: 18, color: "#9a3412", backgroundColor: "#fff7ed", padding: 9, marginTop: 10 },
  bindingSummary: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  selectionMark: { fontSize: 12, fontWeight: "700", color: "#2563eb" },
  skillInstructions: { fontSize: 12, lineHeight: 18, color: "#334155", backgroundColor: "#f8fafc", padding: 9, marginTop: 9 },
  executionSearch: { flexDirection: "row", gap: 10, alignItems: "center" },
  executionDetail: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 8, padding: 14 },
  payloadHeading: { fontSize: 13, fontWeight: "700", color: "#334155", marginTop: 14, marginBottom: 6 },
  payload: { fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }), fontSize: 11, lineHeight: 17, color: "#334155", backgroundColor: "#f8fafc", padding: 10 },
  untrustedHeader: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between" },
  untrustedLabel: { fontSize: 11, fontWeight: "700", color: "#9a3412", backgroundColor: "#ffedd5", paddingHorizontal: 7, paddingVertical: 3, marginBottom: 6 },
  emptyInline: { color: "#64748b", fontSize: 13, lineHeight: 20, paddingVertical: 12 },
  emptyState: { flex: 1, justifyContent: "center", alignItems: "center", padding: 24, backgroundColor: "#f8fafc" },
  emptyTitle: { fontSize: 20, fontWeight: "700", color: "#0f172a", marginBottom: 8 },
  mutedText: { color: "#64748b", textAlign: "center" },
});
