import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#edf2f4",
    padding: 14,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#edf2f4",
    padding: 24,
  },
  centerButton: {
    marginTop: 16,
    minWidth: 180,
  },
  desktopLayout: {
    flex: 1,
    flexDirection: "row",
    gap: 14,
  },
  mobileLayout: {
    flex: 1,
    gap: 12,
  },
  sidebar: {
    width: 350,
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    padding: 14,
  },
  main: {
    flex: 1,
  },
  mainContent: {
    gap: 12,
    paddingBottom: 24,
  },
  panel: {
    backgroundColor: "#ffffff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    padding: 14,
  },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  eyebrow: {
    color: "#0f766e",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  heading: {
    color: "#0f172a",
    fontSize: 26,
    fontWeight: "800",
    marginTop: 4,
  },
  tabRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 14,
    marginBottom: 12,
  },
  tabButton: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: "#f8fafc",
  },
  tabButtonActive: {
    backgroundColor: "#0f766e",
    borderColor: "#0f766e",
  },
  tabButtonText: {
    color: "#334155",
    fontSize: 13,
    fontWeight: "800",
  },
  tabButtonTextActive: {
    color: "#ffffff",
  },
  actionRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  actionButton: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#0f766e",
  },
  secondaryButton: {
    flex: 1,
    borderRadius: 8,
    backgroundColor: "#334155",
  },
  startButton: {
    minWidth: 150,
    borderRadius: 8,
    backgroundColor: "#0f766e",
  },
  workflowButton: {
    minWidth: 150,
    borderRadius: 8,
    backgroundColor: "#264653",
  },
  headerActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  processButton: {
    minWidth: 120,
    borderRadius: 8,
    backgroundColor: "#334155",
  },
  fullButton: {
    borderRadius: 8,
    backgroundColor: "#0f766e",
  },
  notice: {
    color: "#0f766e",
    fontWeight: "700",
    marginBottom: 8,
  },
  threadList: {
    flex: 1,
  },
  threadListContent: {
    gap: 8,
    paddingBottom: 12,
  },
  threadItem: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#f8fafc",
  },
  threadItemActive: {
    backgroundColor: "#264653",
    borderColor: "#264653",
  },
  threadTitle: {
    color: "#0f172a",
    fontWeight: "800",
  },
  threadTitleActive: {
    color: "#ffffff",
  },
  threadMeta: {
    color: "#64748b",
    fontSize: 12,
    marginTop: 4,
    fontWeight: "800",
  },
  threadMetaActive: {
    color: "#cbd5e1",
  },
  threadPreview: {
    color: "#475569",
    marginTop: 8,
    lineHeight: 18,
  },
  threadPreviewActive: {
    color: "#e2e8f0",
  },
  grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  formPanel: {
    flex: 1,
    minWidth: 260,
  },
  listPanel: {
    flex: 0.9,
    minWidth: 320,
  },
  previewPanel: {
    flex: 1.2,
    minWidth: 360,
  },
  contextPanel: {
    flex: 1,
    minWidth: 300,
  },
  sectionTitle: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "800",
  },
  pageSectionTitle: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "900",
    marginTop: 6,
    marginBottom: 10,
  },
  contextLine: {
    color: "#64748b",
    marginTop: 4,
  },
  textArea: {
    minHeight: 116,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  goalInput: {
    minHeight: 106,
    textAlignVertical: "top",
    paddingTop: 12,
  },
  subsectionLabel: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 8,
  },
  segmentRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  segmentRowCompact: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: 8,
  },
  segmentButton: {
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: "#f8fafc",
  },
  segmentActive: {
    backgroundColor: "#0f766e",
    borderColor: "#0f766e",
  },
  segmentText: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  segmentTextActive: {
    color: "#ffffff",
  },
  rowItem: {
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 12,
    marginTop: 12,
  },
  rowTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  rowTitle: {
    color: "#0f172a",
    fontWeight: "800",
    flexShrink: 1,
  },
  rowMeta: {
    color: "#64748b",
    marginTop: 5,
    fontSize: 12,
    fontWeight: "600",
  },
  inlineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 10,
  },
  previewTitle: {
    color: "#0f172a",
    fontSize: 16,
    fontWeight: "800",
    marginTop: 8,
  },
  versionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
  },
  chunkBox: {
    marginTop: 10,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  chunkTitle: {
    color: "#334155",
    fontWeight: "800",
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  statChip: {
    color: "#334155",
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
  },
  taskRow: {
    flexDirection: "row",
    gap: 12,
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 12,
    marginTop: 12,
  },
  taskIndex: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: "#e0f2fe",
    alignItems: "center",
    justifyContent: "center",
  },
  taskIndexText: {
    color: "#0369a1",
    fontWeight: "800",
  },
  taskBody: {
    flex: 1,
  },
  messageBox: {
    marginTop: 10,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  messageBody: {
    color: "#334155",
    marginTop: 8,
    lineHeight: 20,
  },
  approvalBox: {
    marginTop: 12,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    backgroundColor: "#f8fafc",
  },
  inlineActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 10,
  },
  inlineButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#0f766e",
    paddingHorizontal: 10,
    paddingVertical: 7,
    alignSelf: "flex-start",
  },
  inlineButtonText: {
    color: "#0f766e",
    fontWeight: "800",
  },
  approveButton: {
    borderRadius: 8,
    backgroundColor: "#0f766e",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  approveButtonText: {
    color: "#ffffff",
    fontWeight: "800",
  },
  rejectButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#dc2626",
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  rejectButtonText: {
    color: "#dc2626",
    fontWeight: "800",
  },
  statusPill: {
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 5,
    flexShrink: 0,
  },
  statusText: {
    color: "#ffffff",
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  statusReady: {
    backgroundColor: "#0f766e",
  },
  statusRunning: {
    backgroundColor: "#ca8a04",
  },
  statusFailed: {
    backgroundColor: "#dc2626",
  },
  statusNeutral: {
    backgroundColor: "#64748b",
  },
  answerText: {
    color: "#0f172a",
    lineHeight: 22,
    fontSize: 15,
  },
  nextStep: {
    color: "#264653",
    fontWeight: "800",
    lineHeight: 21,
    marginTop: 10,
  },
  warningText: {
    color: "#92400e",
    backgroundColor: "#fef3c7",
    borderRadius: 8,
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 8,
    lineHeight: 20,
    marginTop: 10,
    fontWeight: "700",
  },
  signalBlock: {
    marginTop: 12,
  },
  signalTitle: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 8,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  signalChip: {
    color: "#334155",
    backgroundColor: "#edf2f4",
    borderRadius: 8,
    overflow: "hidden",
    paddingHorizontal: 9,
    paddingVertical: 6,
    fontSize: 12,
    fontWeight: "700",
  },
  traceBlock: {
    marginTop: 14,
  },
  timelineItem: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  timelineDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#0f766e",
    marginTop: 9,
  },
  timelineDotMuted: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#94a3b8",
    marginTop: 9,
  },
  timelineBody: {
    flex: 1,
    borderLeftWidth: 1,
    borderLeftColor: "#e2e8f0",
    paddingLeft: 10,
    paddingBottom: 8,
  },
  toolCallItem: {
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 10,
    marginTop: 10,
  },
  citationContainer: {
    marginTop: 12,
  },
  citationsTitle: {
    color: "#334155",
    fontWeight: "800",
    marginBottom: 8,
  },
  citationItem: {
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 10,
    marginTop: 10,
  },
  citationGroup: {
    marginTop: 10,
  },
  sourceBadge: {
    alignSelf: "flex-start",
    color: "#0f766e",
    backgroundColor: "#ccfbf1",
    borderRadius: 8,
    overflow: "hidden",
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 12,
    fontWeight: "800",
  },
  citationTitle: {
    color: "#0f172a",
    fontWeight: "800",
    flex: 1,
  },
  scoreText: {
    color: "#64748b",
    fontSize: 12,
    fontWeight: "700",
  },
  citationSnippet: {
    color: "#334155",
    lineHeight: 20,
    marginTop: 6,
  },
  contextItem: {
    borderTopWidth: 1,
    borderTopColor: "#e2e8f0",
    paddingTop: 10,
    marginTop: 10,
  },
  contextItemTitle: {
    color: "#334155",
    fontSize: 12,
    fontWeight: "800",
  },
  contextItemBody: {
    color: "#0f172a",
    lineHeight: 20,
    marginTop: 5,
  },
  evalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
  },
  evalCard: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: "#cbd5e1",
    borderRadius: 8,
    padding: 12,
    backgroundColor: "#f8fafc",
  },
  emptyTitle: {
    color: "#0f172a",
    fontSize: 18,
    fontWeight: "800",
  },
  emptyText: {
    color: "#64748b",
    lineHeight: 20,
    marginTop: 8,
  },
  errorText: {
    color: "#dc2626",
    lineHeight: 20,
    marginTop: 6,
  },
});
