import * as Tabs from "@radix-ui/react-tabs";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, FileUp, Link2, RefreshCw, RotateCcw, Search, X } from "lucide-react";
import { useState } from "react";
import { useSearchParams } from "react-router-dom";

import { createFileSource, createTextSource, createURLSource, decideDuplicate, getKnowledgeSource, listDeadLetters, listDuplicates, listKnowledgeSources, listSourceGroups, reingestSource, retryDeadLetter, setCanonicalSource } from "@/api/knowledge";
import { FormError } from "@/components/AuthLayout";
import { PageError, PageLoading } from "@/components/PageState";
import { useOrganization } from "@/organizations/OrganizationProvider";

export function KnowledgePage() {
  const { activeOrganization } = useOrganization(); const orgId = activeOrganization?.id; const queryClient = useQueryClient(); const [params, setParams] = useSearchParams(); const sourceId = Number(params.get("sourceId")) || 0; const [filter, setFilter] = useState("");
  const key = ["organizations", orgId, "knowledge"];
  const sources = useQuery({ queryKey: [...key, "sources"], queryFn: listKnowledgeSources, enabled: Boolean(orgId), refetchInterval: 10_000 });
  const detail = useQuery({ queryKey: [...key, "sources", sourceId], queryFn: () => getKnowledgeSource(sourceId), enabled: Boolean(sourceId) });
  const duplicates = useQuery({ queryKey: [...key, "duplicates"], queryFn: listDuplicates, enabled: Boolean(orgId) });
  const groups = useQuery({ queryKey: [...key, "groups"], queryFn: listSourceGroups, enabled: Boolean(orgId) });
  const deadLetters = useQuery({ queryKey: [...key, "dead-letters"], queryFn: listDeadLetters, enabled: Boolean(orgId) });
  const refresh = () => queryClient.invalidateQueries({ queryKey: key });
  const reingest = useMutation({ mutationFn: reingestSource, onSuccess: refresh }); const retry = useMutation({ mutationFn: retryDeadLetter, onSuccess: refresh }); const duplicateDecision = useMutation({ mutationFn: ({ id, decision }: { id: number; decision: "confirm" | "reject" }) => decideDuplicate(id, decision), onSuccess: refresh });
  const visible = sources.data?.filter((source) => `${source.title} ${source.kind} ${source.status}`.toLowerCase().includes(filter.toLowerCase())) ?? [];
  return <div className="knowledge-page"><header className="page-header"><div><p className="eyebrow">Knowledge</p><h1>知识中心</h1><p>来源、版本、分块、重复候选与失败任务。</p></div><ImportSource onCreated={(id) => { refresh(); setParams({ sourceId: String(id) }); }} /></header><Tabs.Root defaultValue="sources"><Tabs.List className="agent-tab-list knowledge-tabs"><Tabs.Trigger value="sources">来源</Tabs.Trigger><Tabs.Trigger value="duplicates">重复候选 <span>{duplicates.data?.filter((item) => item.status === "pending").length ?? 0}</span></Tabs.Trigger><Tabs.Trigger value="groups">来源组</Tabs.Trigger><Tabs.Trigger value="dead">Dead letters <span>{deadLetters.data?.length ?? 0}</span></Tabs.Trigger></Tabs.List>
    <Tabs.Content value="sources"><div className="knowledge-layout"><aside className="source-list"><div className="search-field"><Search size={16} /><input placeholder="搜索来源" aria-label="搜索来源" value={filter} onChange={(event) => setFilter(event.target.value)} /></div>{sources.isLoading ? <PageLoading /> : sources.isError ? <PageError error={sources.error} /> : visible.map((source) => <button className={sourceId === source.id ? "active" : ""} key={source.id} onClick={() => setParams({ sourceId: String(source.id) })}><div><strong>{source.title}</strong><span>{source.kind} · {source.status}</span></div><span className={`transcription-badge status-${source.status}`}>{source.dedupe_status}</span></button>)}</aside><main className="source-detail">{!sourceId ? <div className="pane-empty">选择知识来源</div> : detail.isLoading ? <PageLoading /> : detail.isError ? <PageError error={detail.error} /> : detail.data && <><header><div><h2>{detail.data.source.title}</h2><p>{detail.data.source.uri || detail.data.source.file_name || detail.data.source.kind}</p></div><button className="button-secondary" onClick={() => reingest.mutate(detail.data!.source.id)}><RefreshCw size={16} />重新索引</button></header>{detail.data.source.last_error && <div className="status-error">{detail.data.source.last_error}</div>}<section><h3>版本</h3><div className="version-list">{detail.data.versions.map((version) => <article key={version.id}><strong>v{version.version}</strong><span>{version.status}</span><span>{version.chunk_count} chunks</span><code>{version.content_hash.slice(0, 12)}</code></article>)}</div></section><section><h3>分块预览</h3><div className="chunk-list">{detail.data.chunks.map((chunk) => <article key={chunk.id}><header><strong>#{chunk.chunk_index}</strong><span>{chunk.index_status}</span></header><p>{chunk.snippet}</p></article>)}</div></section></>}</main></div></Tabs.Content>
    <Tabs.Content value="duplicates" className="knowledge-table"><h2>重复候选</h2>{duplicates.data?.map((item) => <article className="panel data-row" key={item.id}><div><strong>Source #{item.source_id} ↔ #{item.candidate_source_id}</strong><small>{item.duplicate_kind} · similarity {Math.round(item.similarity * 100)}% · {item.status}</small></div>{item.status === "pending" && <div className="button-row"><button className="button-secondary" onClick={() => duplicateDecision.mutate({ id: item.id, decision: "reject" })}><X size={15} />拒绝</button><button className="button-primary" onClick={() => duplicateDecision.mutate({ id: item.id, decision: "confirm" })}><Check size={15} />确认</button></div>}</article>)}</Tabs.Content>
    <Tabs.Content value="groups" className="knowledge-table"><h2>来源组</h2>{groups.data?.map((group) => <SourceGroupRow key={group.id} group={group} refresh={refresh} />)}</Tabs.Content>
    <Tabs.Content value="dead" className="knowledge-table"><h2>Dead letters</h2>{deadLetters.data?.map((item) => <article className="panel data-row" key={item.id}><div><strong>{item.event}</strong><small>{item.aggregate_type} #{item.aggregate_id} · {item.attempts} attempts</small><small className="text-danger">{item.last_error}</small></div><button className="button-secondary" onClick={() => retry.mutate(item.id)}><RotateCcw size={15} />重试</button></article>)}</Tabs.Content>
  </Tabs.Root></div>;
}

function ImportSource({ onCreated }: { onCreated(id: number): void }) { const [open, setOpen] = useState(false); const [kind, setKind] = useState<"text" | "url" | "file">("text"); const [title, setTitle] = useState(""); const [value, setValue] = useState(""); const [file, setFile] = useState<File | null>(null); const mutation = useMutation({ mutationFn: () => kind === "text" ? createTextSource(title, value) : kind === "url" ? createURLSource(title, value) : createFileSource(title, file!), onSuccess: (source) => { setOpen(false); setTitle(""); setValue(""); setFile(null); onCreated(source.id); } }); return <div className="import-control"><button className="button-primary" onClick={() => setOpen(!open)}><FileUp size={17} />导入来源</button>{open && <div className="import-popover"><div className="segmented"><button className={kind === "text" ? "active" : ""} onClick={() => setKind("text")}>文本</button><button className={kind === "url" ? "active" : ""} onClick={() => setKind("url")}>URL</button><button className={kind === "file" ? "active" : ""} onClick={() => setKind("file")}>文件</button></div><FormError error={mutation.error} /><label>标题<input className="field" value={title} onChange={(event) => setTitle(event.target.value)} /></label>{kind === "text" && <label>正文<textarea className="field" rows={5} value={value} onChange={(event) => setValue(event.target.value)} /></label>}{kind === "url" && <label>URL<div className="input-icon"><Link2 size={16} /><input type="url" value={value} onChange={(event) => setValue(event.target.value)} /></div></label>}{kind === "file" && <label>文件<input className="field" type="file" accept=".txt,.md,.html,.pdf,text/plain,text/markdown,text/html,application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /></label>}<button className="button-primary w-full" disabled={!title || (kind === "file" ? !file : !value)} onClick={() => mutation.mutate()}>开始导入</button></div>}</div>; }
function SourceGroupRow({ group, refresh }: { group: Awaited<ReturnType<typeof listSourceGroups>>[number]; refresh(): void }) { const [sourceId, setSourceId] = useState(String(group.canonical_source_id ?? "")); const mutation = useMutation({ mutationFn: () => setCanonicalSource(group.id, Number(sourceId)), onSuccess: refresh }); return <article className="panel data-row"><div><strong>{group.title}</strong><small>{group.status} · canonical #{group.canonical_source_id ?? "-"}</small></div><div className="canonical-control"><input className="field" inputMode="numeric" placeholder="Source ID" value={sourceId} onChange={(event) => setSourceId(event.target.value)} /><button className="button-secondary" disabled={!sourceId} onClick={() => mutation.mutate()}>设为 canonical</button></div></article>; }
